import Ptx

/-! Public proof dependencies, consumed by `scripts/check.sh`. -/
#print axioms Ptx.step_exists
#print axioms Ptx.step_deterministic
#print axioms Ptx.load_writes_destination
#print axioms Ptx.store_emits_operand
#print axioms Ptx.execute_runs
#print axioms Ptx.runs_eq_execute
#print axioms Ptx.runs_exists
#print axioms Ptx.runs_deterministic
#print axioms Ptx.execute_effects
#print axioms Ptx.execute_getElem?
#print axioms Ptx.execute_access_safe
#print axioms Ptx.word_footprints_disjoint
#print axioms Ptx.Program.all_threads_run
#print axioms Ptx.Program.events_origin
#print axioms Ptx.Program.graph_event_origin
#print axioms Ptx.Program.load_origin
#print axioms Ptx.Program.store_origin
#print axioms Ptx.Program.initial_origin
#print axioms Ptx.Program.no_invented_values
#print axioms Ptx.Program.admitted_access_safe
#print axioms Ptx.Graph.single_copy
#print axioms Ptx.Graph.no_source_coherence_predecessor
#print axioms Ptx.Graph.valid_of_certificate
#print axioms Ptx.MessagePassing.publication
#print axioms Ptx.MessagePassing.publication_observed
#print axioms Ptx.MessagePassing.successful_execution_exists
#print axioms Ptx.MessagePassing.relaxed_counterexample_exists
#print axioms Ptx.MessagePassing.memory_safe
#print axioms Ptx.MessagePassing.objects_disjoint
#print axioms Ptx.MessagePassing.local_completion
#print axioms Ptx.MessagePassing.acquire_stale_impossible

/-! Exact checking, complete outcomes, and the additional litmus suite. -/
#print axioms Ptx.reachable_iff
#print axioms Ptx.Graph.baseCheck_iff
#print axioms Ptx.Graph.causeCheck_iff
#print axioms Ptx.Graph.locationCheck_iff
#print axioms Ptx.Graph.check_iff
#print axioms Ptx.Graph.check_false_iff
#print axioms Ptx.MessagePassing.source_values
#print axioms Ptx.MessagePassing.acquire_outcomes
#print axioms Ptx.MessagePassing.relaxed_outcomes
#print axioms Ptx.MessagePassing.zero_flag_check
#print axioms Ptx.MessagePassing.relaxed_check
#print axioms Ptx.MessagePassing.acquire_success_check
#print axioms Ptx.MessagePassing.acquire_stale_check
#print axioms Ptx.CheckerExamples.empty_relation
#print axioms Ptx.CheckerExamples.singleton_loop
#print axioms Ptx.CheckerExamples.cycle_reachable
#print axioms Ptx.CheckerExamples.empty_graph_accepted
#print axioms Ptx.CheckerExamples.initialized_graph_accepted
#print axioms Ptx.CheckerExamples.read_cannot_source_itself
#print axioms Ptx.CheckerExamples.reflexive_coherence_rejected
#print axioms Ptx.CheckerExamples.wrong_value_rejected
#print axioms Ptx.CheckerExamples.wrong_address_rejected
#print axioms Ptx.CheckerExamples.missing_initial_coherence_rejected
#print axioms Ptx.CheckerExamples.wrong_value_invalid
#print axioms Ptx.CheckerExamples.base_cycle_detected
#print axioms Ptx.CheckerExamples.base_cycle_rejected
#print axioms Ptx.Litmus.StoreBuffering.both_zero_exists
#print axioms Ptx.Litmus.StoreBuffering.memory_safe
#print axioms Ptx.Litmus.SameLocation.ordered_read
#print axioms Ptx.Litmus.SameLocation.stale_impossible
#print axioms Ptx.Litmus.SameLocation.execution_exists
#print axioms Ptx.Litmus.SameLocation.memory_safe
#print axioms Ptx.Litmus.ReleasePair.publication_observed
#print axioms Ptx.Litmus.ReleasePair.execution_exists
#print axioms Ptx.Litmus.ReleasePair.no_direct_release_observation
#print axioms Ptx.Litmus.ReleasePair.memory_safe
#print axioms Ptx.Litmus.AcquirePair.publication_observed
#print axioms Ptx.Litmus.AcquirePair.execution_exists
#print axioms Ptx.Litmus.AcquirePair.no_direct_release_observation
#print axioms Ptx.Litmus.AcquirePair.memory_safe
#print axioms Ptx.Litmus.ReleasePair.pair_required
#print axioms Ptx.Litmus.AcquirePair.pair_required
#print axioms Ptx.Litmus.ReleasePair.witness_synchronizes
#print axioms Ptx.Litmus.AcquirePair.witness_synchronizes
