import Ptx

/-! Public proof dependencies, consumed by `scripts/check.sh`. -/
#print axioms Ptx.step_exists
#print axioms Ptx.step_deterministic
#print axioms Ptx.load_writes_destination
#print axioms Ptx.store_emits_operand
#print axioms Ptx.execute_runs
#print axioms Ptx.runs_eq_execute
#print axioms Ptx.runs_exists
#print axioms Ptx.runs_deterministic
#print axioms Ptx.execute_effects
#print axioms Ptx.execute_getElem?
#print axioms Ptx.execute_access_safe
#print axioms Ptx.word_footprints_disjoint
#print axioms Ptx.Program.all_threads_run
#print axioms Ptx.Program.events_origin
#print axioms Ptx.Program.graph_event_origin
#print axioms Ptx.Program.load_origin
#print axioms Ptx.Program.store_origin
#print axioms Ptx.Program.initial_origin
#print axioms Ptx.Program.no_invented_values
#print axioms Ptx.Program.admitted_access_safe
#print axioms Ptx.Graph.single_copy
#print axioms Ptx.Graph.no_source_coherence_predecessor
#print axioms Ptx.Graph.valid_of_certificate
#print axioms Ptx.MessagePassing.publication
#print axioms Ptx.MessagePassing.publication_observed
#print axioms Ptx.MessagePassing.successful_execution_exists
#print axioms Ptx.MessagePassing.relaxed_counterexample_exists
#print axioms Ptx.MessagePassing.memory_safe
#print axioms Ptx.MessagePassing.objects_disjoint
#print axioms Ptx.MessagePassing.local_completion
#print axioms Ptx.MessagePassing.acquire_stale_impossible

/-! Exact checking, complete outcomes, and the additional litmus suite. -/
#print axioms Ptx.reachable_iff
#print axioms Ptx.Graph.baseCheck_iff
#print axioms Ptx.Graph.causeCheck_iff
#print axioms Ptx.Graph.locationCheck_iff
#print axioms Ptx.Graph.check_iff
#print axioms Ptx.Graph.check_false_iff
#print axioms Ptx.MessagePassing.source_values
#print axioms Ptx.MessagePassing.acquire_outcomes
#print axioms Ptx.MessagePassing.relaxed_outcomes
#print axioms Ptx.MessagePassing.zero_flag_check
#print axioms Ptx.MessagePassing.relaxed_check
#print axioms Ptx.MessagePassing.acquire_success_check
#print axioms Ptx.MessagePassing.acquire_stale_check
#print axioms Ptx.CheckerExamples.empty_relation
#print axioms Ptx.CheckerExamples.singleton_loop
#print axioms Ptx.CheckerExamples.cycle_reachable
#print axioms Ptx.CheckerExamples.empty_graph_accepted
#print axioms Ptx.CheckerExamples.initialized_graph_accepted
#print axioms Ptx.CheckerExamples.read_cannot_source_itself
#print axioms Ptx.CheckerExamples.reflexive_coherence_rejected
#print axioms Ptx.CheckerExamples.wrong_value_rejected
#print axioms Ptx.CheckerExamples.wrong_address_rejected
#print axioms Ptx.CheckerExamples.missing_initial_coherence_rejected
#print axioms Ptx.CheckerExamples.wrong_value_invalid
#print axioms Ptx.CheckerExamples.base_cycle_detected
#print axioms Ptx.CheckerExamples.base_cycle_rejected
#print axioms Ptx.Litmus.StoreBuffering.both_zero_exists
#print axioms Ptx.Litmus.StoreBuffering.memory_safe
#print axioms Ptx.Litmus.SameLocation.ordered_read
#print axioms Ptx.Litmus.SameLocation.stale_impossible
#print axioms Ptx.Litmus.SameLocation.execution_exists
#print axioms Ptx.Litmus.SameLocation.memory_safe
#print axioms Ptx.Litmus.ReleasePair.publication_observed
#print axioms Ptx.Litmus.ReleasePair.execution_exists
#print axioms Ptx.Litmus.ReleasePair.no_direct_release_observation
#print axioms Ptx.Litmus.ReleasePair.memory_safe
#print axioms Ptx.Litmus.AcquirePair.publication_observed
#print axioms Ptx.Litmus.AcquirePair.execution_exists
#print axioms Ptx.Litmus.AcquirePair.no_direct_release_observation
#print axioms Ptx.Litmus.AcquirePair.memory_safe
#print axioms Ptx.Litmus.ReleasePair.pair_required
#print axioms Ptx.Litmus.AcquirePair.pair_required
#print axioms Ptx.Litmus.ReleasePair.witness_synchronizes
#print axioms Ptx.Litmus.AcquirePair.witness_synchronizes

/-! Explicit environments, scoped constraints, scalar execution and kernel bridges. -/

-- Environment
#print axioms Ptx.Scope.includes_self
#print axioms Ptx.Scope.cta_includes_cluster
#print axioms Ptx.Scope.cluster_includes_gpu
#print axioms Ptx.Environment.accessible_contract
#print axioms Ptx.Environment.accessible_bounds

-- ScopedMemory
#print axioms Ptx.ScopedGraph.morallyStrong_legacy
#print axioms Ptx.ScopedGraph.observation_legacy
#print axioms Ptx.ScopedGraph.sync_legacy
#print axioms Ptx.ScopedGraph.base_legacy
#print axioms Ptx.ScopedGraph.cause_legacy
#print axioms Ptx.ScopedGraph.location_legacy
#print axioms Ptx.ScopedGraph.coherent_legacy
#print axioms Ptx.ScopedGraph.valid_legacy

-- ScopedExamples
#print axioms Ptx.ScopedExamples.publication
#print axioms Ptx.ScopedExamples.gpu_all_in_scope
#print axioms Ptx.ScopedExamples.gpu_specialization
#print axioms Ptx.ScopedExamples.in_scope_execution_exists
#print axioms Ptx.ScopedExamples.outside_scope_execution_exists
#print axioms Ptx.ScopedExamples.outside_scope_no_sync
#print axioms Ptx.ScopedExamples.scope_inclusion_is_mutual
#print axioms Ptx.ScopedExamples.different_grids_not_same_cta
#print axioms Ptx.ScopedExamples.different_grids_same_gpu
#print axioms Ptx.ScopedExamples.same_cluster_different_cta
#print axioms Ptx.ScopedExamples.shared_owner_can_access
#print axioms Ptx.ScopedExamples.shared_other_cta_cannot_access
#print axioms Ptx.ScopedExamples.explicit_cluster_shared_access
#print axioms Ptx.ScopedExamples.shared_other_grid_cannot_access
#print axioms Ptx.ScopedExamples.misalignment_rejected
#print axioms Ptx.ScopedExamples.bounds_rejected
#print axioms Ptx.ScopedExamples.cluster_target_rejected
#print axioms Ptx.ScopedExamples.cluster_target_accepted
#print axioms Ptx.ScopedExamples.local_other_thread_rejected
#print axioms Ptx.ScopedExamples.entry_parameter_store_rejected
#print axioms Ptx.ScopedExamples.parameter_abi_explicitly_unsupported
#print axioms Ptx.ScopedExamples.racy_writes_partial_coherence
#print axioms Ptx.ScopedExamples.racy_program_admitted
#print axioms Ptx.ScopedExamples.racy_not_legacy_valid

-- Scalar
#print axioms Ptx.Scalar.update_same
#print axioms Ptx.Scalar.update_other
#print axioms Ptx.Scalar.addressIndex_ok_iff
#print axioms Ptx.Scalar.runWith_sound
#print axioms Ptx.Scalar.run_sound
#print axioms Ptx.Scalar.runWith_trace_length
#print axioms Ptx.Scalar.run_zero
#print axioms Ptx.Scalar.eval_skipped
#print axioms Ptx.Scalar.shift_left_clamped
#print axioms Ptx.Scalar.shift_right_clamped
#print axioms Ptx.Scalar.run_succ
#print axioms Ptx.Scalar.run_add
#print axioms Ptx.Scalar.eval_memory_safe
#print axioms Ptx.Scalar.eval_memory_length
#print axioms Ptx.Scalar.step_memory_safe
#print axioms Ptx.Scalar.step_memory_length
#print axioms Ptx.Scalar.eval_halted
#print axioms Ptx.Scalar.step_halted
#print axioms Ptx.Scalar.runWith_memory_length
#print axioms Ptx.Scalar.run_memory_length
#print axioms Ptx.Scalar.runWith_trace_safe
#print axioms Ptx.Scalar.run_trace_safe
#print axioms Ptx.Scalar.Runs.exists_run
#print axioms Ptx.Scalar.add_modulo
#print axioms Ptx.Scalar.sub_modulo
#print axioms Ptx.Scalar.mul_low_modulo
#print axioms Ptx.Scalar.add64_modulo
#print axioms Ptx.Scalar.validAddress_bytes
#print axioms Ptx.Scalar.unsupported_not_hidden
#print axioms Ptx.Scalar.shift_boundary_examples
#print axioms Ptx.Scalar.unsigned_wrap_examples

-- ScalarText
#print axioms Ptx.Scalar.Text.decode_encode
#print axioms Ptx.Scalar.Text.bare_load_rejected
#print axioms Ptx.Scalar.Text.uniform_branch_rejected
#print axioms Ptx.Scalar.Text.wrong_destination_rejected
#print axioms Ptx.Scalar.Text.decodeOp_supported
#print axioms Ptx.Scalar.Text.immediate_store_rejected
#print axioms Ptx.Scalar.Text.decode_supported

-- ScalarKernels
#print axioms Ptx.Scalar.Kernels.add_lane_result
#print axioms Ptx.Scalar.Kernels.elementwise_add
#print axioms Ptx.Scalar.Kernels.loop_zero
#print axioms Ptx.Scalar.Kernels.loop_advance
#print axioms Ptx.Scalar.Kernels.sum_loop_correct
#print axioms Ptx.Scalar.Kernels.add_lane_exists
#print axioms Ptx.Scalar.Kernels.sum_loop_exists
#print axioms Ptx.Scalar.Kernels.sum_loop_extra_fuel
#print axioms Ptx.Scalar.Kernels.sum_loop_memory_safe

-- ScalarEnvironment
#print axioms Ptx.Scalar.arena_access_iff
#print axioms Ptx.Scalar.run_environment_safe
#print axioms Ptx.Scalar.separate_arenas
#print axioms Ptx.Scalar.arena_forms_eligible

-- ScalarExamples
#print axioms Ptx.Scalar.Examples.zero_count_no_access
#print axioms Ptx.Scalar.Examples.modular_sum
#print axioms Ptx.Scalar.Examples.fuel_exhaustion_is_not_halt
#print axioms Ptx.Scalar.Examples.misaligned_load_fault
#print axioms Ptx.Scalar.Examples.out_of_bounds_load_fault
#print axioms Ptx.Scalar.Examples.skipped_load_no_fault
#print axioms Ptx.Scalar.Examples.invalid_pc_is_explicit
#print axioms Ptx.Scalar.Examples.unsupported_is_explicit
#print axioms Ptx.Scalar.Examples.add_lane_text_roundtrip
#print axioms Ptx.Scalar.Examples.sum_loop_text_roundtrip

-- ScalarMemoryWitness
#print axioms Ptx.Scalar.MemoryWitness.events_eq
#print axioms Ptx.Scalar.MemoryWitness.graph_event
#print axioms Ptx.Scalar.MemoryWitness.graph_source
#print axioms Ptx.Scalar.MemoryWitness.graph_event0
#print axioms Ptx.Scalar.MemoryWitness.graph_event1
#print axioms Ptx.Scalar.MemoryWitness.graph_event2
#print axioms Ptx.Scalar.MemoryWitness.graph_event3
#print axioms Ptx.Scalar.MemoryWitness.graph_event4
#print axioms Ptx.Scalar.MemoryWitness.graph_event5
#print axioms Ptx.Scalar.MemoryWitness.candidate_result
#print axioms Ptx.Scalar.MemoryWitness.input_sources
#print axioms Ptx.Scalar.MemoryWitness.candidate_correct
#print axioms Ptx.Scalar.MemoryWitness.witness_valid
#print axioms Ptx.Scalar.MemoryWitness.candidate_eq_concrete
#print axioms Ptx.Scalar.MemoryWitness.label_preserves_address
#print axioms Ptx.Scalar.MemoryWitness.witness_events_from_run
#print axioms Ptx.Scalar.MemoryWitness.constructive_execution

/-! Reusable proof rules and shared-allocation vector addition. -/

-- ScalarRules
#print axioms Ptx.Scalar.Rules.segment_comp
#print axioms Ptx.Scalar.Rules.segment_then_completed
#print axioms Ptx.Scalar.Rules.segment_then_total
#print axioms Ptx.Scalar.Rules.completed_total
#print axioms Ptx.Scalar.Rules.eval_frame
#print axioms Ptx.Scalar.Rules.step_frame
#print axioms Ptx.Scalar.Rules.runWith_frame
#print axioms Ptx.Scalar.Rules.run_frame
#print axioms Ptx.Scalar.Rules.runWith_invariant
#print axioms Ptx.Scalar.Rules.partial_of_invariant
#print axioms Ptx.Scalar.Rules.terminates_of_decreasing_measure

-- SharedVector
#print axioms Ptx.Scalar.SharedVector.replace_same
#print axioms Ptx.Scalar.SharedVector.replace_other
#print axioms Ptx.Scalar.SharedVector.initial_invariant
#print axioms Ptx.Scalar.SharedVector.output_ne_left
#print axioms Ptx.Scalar.SharedVector.output_ne_right
#print axioms Ptx.Scalar.SharedVector.output_injective
#print axioms Ptx.Scalar.SharedVector.get_set_other
#print axioms Ptx.Scalar.SharedVector.get_set_same
#print axioms Ptx.Scalar.SharedVector.advance_other
#print axioms Ptx.Scalar.SharedVector.advance_frame
#print axioms Ptx.Scalar.SharedVector.advance_invariant
#print axioms Ptx.Scalar.SharedVector.execute_invariant
#print axioms Ptx.Scalar.SharedVector.execute_frame
#print axioms Ptx.Scalar.SharedVector.completed_correct
#print axioms Ptx.Scalar.SharedVector.pointer_index
#print axioms Ptx.Scalar.SharedVector.advance_is_scalar_step
#print axioms Ptx.Scalar.SharedVector.exit_is_scalar_step
#print axioms Ptx.Scalar.SharedVector.scheduled_access_safe
#print axioms Ptx.Scalar.SharedVector.cursor_advance
#print axioms Ptx.Scalar.SharedVector.execute_cursor
#print axioms Ptx.Scalar.SharedVector.schedule_length
#print axioms Ptx.Scalar.SharedVector.schedule_complete
#print axioms Ptx.Scalar.SharedVector.faithful_step
#print axioms Ptx.Scalar.SharedVector.execute_faithful
#print axioms Ptx.Scalar.SharedVector.completed_execution_exists
#print axioms Ptx.Scalar.SharedVector.emitted_canonical
#print axioms Ptx.Scalar.SharedVector.emitted_thread
#print axioms Ptx.Scalar.SharedVector.filter_emitted
#print axioms Ptx.Scalar.SharedVector.trace_correspondence
#print axioms Ptx.Scalar.SharedVector.completed_trace
#print axioms Ptx.Scalar.SharedVector.emitted_access_safe
#print axioms Ptx.Scalar.SharedVector.trace_access_safe

-- SharedVectorExamples
#print axioms Ptx.Scalar.SharedVector.Examples.round_robin_result
#print axioms Ptx.Scalar.SharedVector.Examples.uneven_result
#print axioms Ptx.Scalar.SharedVector.Examples.unfair_schedule_incomplete
#print axioms Ptx.Scalar.SharedVector.Examples.concrete_execution_exists
#print axioms Ptx.Scalar.SharedVector.Examples.empty_arena_not_faithful
#print axioms Ptx.Scalar.Rules.Examples.set_segment
#print axioms Ptx.Scalar.Rules.Examples.exit_segment
#print axioms Ptx.Scalar.Rules.Examples.composed_completion
#print axioms Ptx.Scalar.Rules.Examples.composed_frame

-- SharedVectorMemory
#print axioms Ptx.Scalar.SharedVectorMemory.lane_index
#print axioms Ptx.Scalar.SharedVectorMemory.slot_index
#print axioms Ptx.Scalar.SharedVectorMemory.index_eta
#print axioms Ptx.Scalar.SharedVectorMemory.index_eq
#print axioms Ptx.Scalar.SharedVectorMemory.forall_index_iff
#print axioms Ptx.Scalar.SharedVectorMemory.exists_index_iff
#print axioms Ptx.Scalar.SharedVectorMemory.event0
#print axioms Ptx.Scalar.SharedVectorMemory.event1
#print axioms Ptx.Scalar.SharedVectorMemory.event2
#print axioms Ptx.Scalar.SharedVectorMemory.event3
#print axioms Ptx.Scalar.SharedVectorMemory.event4
#print axioms Ptx.Scalar.SharedVectorMemory.event5
#print axioms Ptx.Scalar.SharedVectorMemory.graph_event
#print axioms Ptx.Scalar.SharedVectorMemory.witness_valid
#print axioms Ptx.Scalar.SharedVectorMemory.shared_trace_labels
#print axioms Ptx.Scalar.SharedVectorMemory.verified_shared_execution
#print axioms Ptx.Scalar.SharedVectorMemory.initial_labels
#print axioms Ptx.Scalar.SharedVectorMemory.input_writer
#print axioms Ptx.Scalar.SharedVectorMemory.input_sources
#print axioms Ptx.Scalar.SharedVectorMemory.candidate_event_eq
#print axioms Ptx.Scalar.SharedVectorMemory.candidate_shared_trace_labels
#print axioms Ptx.Scalar.SharedVectorMemory.candidate_output

/-! Bytewise observations, atomicity and exact whole-word specialization. -/

-- ByteMemory
#print axioms Ptx.word_eq_of_bytes
#print axioms Ptx.ByteGraph.rf_projection
#print axioms Ptx.ByteGraph.readsWhole_projection
#print axioms Ptx.ByteGraph.observation_projection
#print axioms Ptx.ByteGraph.sync_projection
#print axioms Ptx.ByteGraph.base_projection
#print axioms Ptx.ByteGraph.cause_projection
#print axioms Ptx.ByteGraph.communication_projection
#print axioms Ptx.ByteGraph.location_projection
#print axioms Ptx.ByteGraph.sources_projection
#print axioms Ptx.ByteGraph.coherent_projection
#print axioms Ptx.ByteGraph.projection_valid_iff
#print axioms Ptx.ByteGraph.ofScoped_uniform
#print axioms Ptx.ByteGraph.ofScoped_valid_iff
#print axioms Ptx.ByteGraph.uniform_policy_independent
#print axioms Ptx.ByteGraph.coherence_later_not_initial
#print axioms Ptx.ByteGraph.sources_uniform_at
#print axioms Ptx.ByteGraph.uniform_of_all_in_scope
#print axioms Ptx.ByteGraph.all_in_scope_valid_iff
#print axioms Ptx.Program.byteGraph_access_safe

-- ByteExamples
#print axioms Ptx.ByteExamples.result_eq
#print axioms Ptx.ByteExamples.little_endian_example
#print axioms Ptx.ByteExamples.torn_valid
#print axioms Ptx.ByteExamples.torn_value_is_new
#print axioms Ptx.ByteExamples.torn_execution_exists
#print axioms Ptx.ByteExamples.in_scope_torn_forbidden
#print axioms Ptx.ByteExamples.torn_projection_invalid
#print axioms Ptx.ByteExamples.equal_value_not_uniform
#print axioms Ptx.ByteExamples.memory_safe

#print axioms Ptx.Graph.direct_sync
#print axioms Ptx.Graph.publication_cause
#print axioms Ptx.Graph.source_of_latest
#print axioms Ptx.Graph.value_of_source
#print axioms Ptx.Graph.source_of_initial_or_write
#print axioms Ptx.Scalar.IntegerMinMax.min_toNat
#print axioms Ptx.Scalar.IntegerMinMax.max_toNat
#print axioms Ptx.Scalar.IntegerMinMax.min_mem
#print axioms Ptx.Scalar.IntegerMinMax.max_mem
#print axioms Ptx.Scalar.IntegerMinMax.min_comm
#print axioms Ptx.Scalar.IntegerMinMax.max_comm
#print axioms Ptx.Scalar.IntegerMinMax.min_idem
#print axioms Ptx.Scalar.IntegerMinMax.max_idem
#print axioms Ptx.Scalar.IntegerMinMax.min_bounds
#print axioms Ptx.Scalar.IntegerMinMax.max_bounds
#print axioms Ptx.Scalar.IntegerMinMax.min_exec
#print axioms Ptx.Scalar.IntegerMinMax.max_exec
#print axioms Ptx.Scalar.IntegerMinMax.min_exec_preserves_other
#print axioms Ptx.Scalar.IntegerMinMax.max_exec_preserves_other
#print axioms Ptx.Scalar.IntegerMinMax.min_false
#print axioms Ptx.Scalar.IntegerMinMax.max_false
#print axioms Ptx.Scalar.Ordered.run_sound
#print axioms Ptx.Scalar.Ordered.run_safe
#print axioms Ptx.Scalar.Ordered.skipped_no_label
#print axioms Ptx.Scalar.Ordered.label_origin
#print axioms Ptx.Scalar.Ordered.label_byte_address
#print axioms Ptx.Scalar.Ordered.label_complete
#print axioms Ptx.Scalar.Ordered.events_origin
#print axioms Ptx.Scalar.Ordered.decode_encode
#print axioms Ptx.Scalar.Ordered.literal_store_rejected
#print axioms Ptx.Scalar.ComputedPublication.events_eq
#print axioms Ptx.Scalar.ComputedPublication.graph_event
#print axioms Ptx.Scalar.ComputedPublication.graph_source
#print axioms Ptx.Scalar.ComputedPublication.event0
#print axioms Ptx.Scalar.ComputedPublication.event1
#print axioms Ptx.Scalar.ComputedPublication.event2
#print axioms Ptx.Scalar.ComputedPublication.event3
#print axioms Ptx.Scalar.ComputedPublication.event4
#print axioms Ptx.Scalar.ComputedPublication.event5
#print axioms Ptx.Scalar.ComputedPublication.event6
#print axioms Ptx.Scalar.ComputedPublication.event7
#print axioms Ptx.Scalar.ComputedPublication.event8
#print axioms Ptx.Scalar.ComputedPublication.event9
#print axioms Ptx.Scalar.ComputedPublication.fin_cases
#print axioms Ptx.Scalar.ComputedPublication.input_sources
#print axioms Ptx.Scalar.ComputedPublication.run_results
#print axioms Ptx.Scalar.ComputedPublication.publication
#print axioms Ptx.Scalar.ComputedPublication.publication_observed
#print axioms Ptx.Scalar.ComputedPublication.success_valid
#print axioms Ptx.Scalar.ComputedPublication.stale_valid
#print axioms Ptx.Scalar.ComputedPublication.success_values_grounded
#print axioms Ptx.Scalar.ComputedPublication.stale_values_grounded
#print axioms Ptx.Scalar.ComputedPublication.success_value_acyclic
#print axioms Ptx.Scalar.ComputedPublication.stale_value_acyclic
#print axioms Ptx.Scalar.ComputedPublication.producer_concrete
#print axioms Ptx.Scalar.ComputedPublication.successful_execution
#print axioms Ptx.Scalar.ComputedPublication.relaxed_counterexample
#print axioms Ptx.Scalar.ComputedPublication.producer_safe
#print axioms Ptx.Scalar.ComputedPublication.consumer_safe
#print axioms Ptx.Scalar.ComputedPublication.graph_memory_safe
#print axioms Ptx.Barrier.reset_invariant
#print axioms Ptx.Barrier.initial_invariant
#print axioms Ptx.Barrier.mark_waiting
#print axioms Ptx.Barrier.mark_other
#print axioms Ptx.Barrier.mark_monotone
#print axioms Ptx.Barrier.missing_prevents_completion
#print axioms Ptx.Barrier.wrong_key_unchanged
#print axioms Ptx.Barrier.old_generation_unchanged
#print axioms Ptx.Barrier.other_cta_unchanged
#print axioms Ptx.Barrier.duplicate_wait_unchanged
#print axioms Ptx.Barrier.completing_step
#print axioms Ptx.Barrier.waiting_step
#print axioms Ptx.Barrier.released_iff
#print axioms Ptx.Barrier.missing_other_blocks_release
#print axioms Ptx.Barrier.release_resets
#print axioms Ptx.Barrier.release_all_runnable
#print axioms Ptx.Barrier.step_invariant
#print axioms Ptx.Barrier.arrival_monotone_in_generation
#print axioms Ptx.Barrier.arrival_event_iff
#print axioms Ptx.Barrier.completion_event_iff
#print axioms Ptx.Barrier.complete_iff_all_warps
#print axioms Ptx.Barrier.run_sound
#print axioms Ptx.Barrier.runs_eq_run
#print axioms Ptx.Barrier.runs_append
#print axioms Ptx.Barrier.runs_invariant
#print axioms Ptx.Barrier.reachable_invariant
#print axioms Ptx.Barrier.prefix_zero
#print axioms Ptx.Barrier.mark_prefix
#print axioms Ptx.Barrier.complete_prefix_iff
#print axioms Ptx.Barrier.prefix_step
#print axioms Ptx.Barrier.prefix_execution
#print axioms Ptx.Barrier.round_exists
#print axioms Ptx.Barrier.successive_reuse
#print axioms Ptx.CollectiveOrder.Certificate.edge_increases
#print axioms Ptx.CollectiveOrder.Certificate.path_increases
#print axioms Ptx.CollectiveOrder.Certificate.split_acyclic
#print axioms Ptx.CollectiveOrder.Certificate.cross_path
#print axioms Ptx.CollectiveOrder.Certificate.cross_increases
#print axioms Ptx.CollectiveOrder.Certificate.projected_path_increases
#print axioms Ptx.CollectiveOrder.Certificate.projected_acyclic
#print axioms Ptx.Graph.Ordered.base_mono
#print axioms Ptx.Graph.Ordered.cause_mono
#print axioms Ptx.Graph.Ordered.valid_restrict
#print axioms Ptx.Graph.Ordered.original_base
#print axioms Ptx.Graph.Ordered.original_cause
#print axioms Ptx.Graph.Ordered.valid_original
#print axioms Ptx.Graph.Ordered.empty_base_iff
#print axioms Ptx.Graph.Ordered.empty_cause_iff
#print axioms Ptx.Graph.Ordered.empty_valid_iff
#print axioms Ptx.Graph.Ordered.derived_valid_iff
#print axioms Ptx.Graph.Ordered.extra_cause
#print axioms Ptx.Graph.Ordered.source_of_latest
#print axioms Ptx.Graph.Ordered.value_of_latest
#print axioms Ptx.Graph.Ordered.valid_of_certificate
#print axioms Ptx.Graph.Ordered.Examples.unordered_valid
#print axioms Ptx.Graph.Ordered.Examples.ordered_fresh_valid
#print axioms Ptx.Graph.Ordered.Examples.ordered_stale_invalid
#print axioms Ptx.Graph.Ordered.Examples.extension_distinguishes
#print axioms Ptx.CollectiveMemory.base_acyclic
#print axioms Ptx.CollectiveMemory.cross_cause
#print axioms Ptx.CollectiveMemory.source_after_phase
#print axioms Ptx.CollectiveMemory.value_after_phase

/-! Shared barrier execution, memory coupling, and delegated bit counts. -/
#print axioms Ptx.SharedBarrier.project_store
#print axioms Ptx.SharedBarrier.project_read
#print axioms Ptx.SharedBarrier.candidate_graph_trace
#print axioms Ptx.SharedBarrier.phase_path_in_trace
#print axioms Ptx.SharedBarrier.cross_origin
#print axioms Ptx.SharedBarrier.candidate_publication
#print axioms Ptx.SharedBarrier.completed_candidate_publication
#print axioms Ptx.SharedBarrier.all_in_scope
#print axioms Ptx.SharedBarrier.observation_scope
#print axioms Ptx.SharedBarrier.initial_graph_label
#print axioms Ptx.SharedBarrier.concrete_eq_candidate
#print axioms Ptx.SharedBarrier.step_environment
#print axioms Ptx.SharedBarrier.trace_accessible
#print axioms Ptx.SharedBarrier.verified_execution
#print axioms Ptx.SharedBarrier.two_warp_verified
#print axioms Ptx.SharedBarrier.accessSafe_bytes
#print axioms Ptx.SharedBarrier.arena_accessible
#print axioms Ptx.SharedBarrier.emitted_accessible
#print axioms Ptx.SharedBarrier.Frame.refl
#print axioms Ptx.SharedBarrier.Frame.trans
#print axioms Ptx.SharedBarrier.Frame.fetched_preserves_input
#print axioms Ptx.SharedBarrier.Frame.dispatch_frame
#print axioms Ptx.SharedBarrier.Frame.step_frame
#print axioms Ptx.SharedBarrier.Frame.run_frame
#print axioms Ptx.SharedBarrier.Frame.initialized
#print axioms Ptx.SharedBarrier.Frame.step_memory_fields
#print axioms Ptx.SharedBarrier.Frame.step_initial_fields
#print axioms Ptx.SharedBarrier.Frame.trace_memory_fields
#print axioms Ptx.SharedBarrier.Frame.step_output
#print axioms Ptx.SharedBarrier.Frame.run_output
#print axioms Ptx.SharedBarrier.Frame.start_control
#print axioms Ptx.SharedBarrier.Frame.initialized_output
#print axioms Ptx.SharedBarrier.Frame.halted_output
#print axioms Ptx.SharedBarrier.Frame.halted_memory_counts
#print axioms Ptx.SharedBarrier.History.memory_member
#print axioms Ptx.SharedBarrier.History.arrival_member
#print axioms Ptx.SharedBarrier.History.completion_member
#print axioms Ptx.SharedBarrier.History.barrier_key
#print axioms Ptx.SharedBarrier.History.store_fields
#print axioms Ptx.SharedBarrier.History.counted_store
#print axioms Ptx.SharedBarrier.History.arrival_path
#print axioms Ptx.SharedBarrier.History.completing_events
#print axioms Ptx.SharedBarrier.History.completion_path
#print axioms Ptx.SharedBarrier.History.load_path
#print axioms Ptx.SharedBarrier.History.completed_memory_accounting
#print axioms Ptx.SharedBarrier.Control.initial
#print axioms Ptx.SharedBarrier.Control.clear_after
#print axioms Ptx.SharedBarrier.Control.live_before
#print axioms Ptx.SharedBarrier.Control.phase_at_barrier
#print axioms Ptx.SharedBarrier.Control.all_at_barrier
#print axioms Ptx.SharedBarrier.Control.congr
#print axioms Ptx.SharedBarrier.Control.advance_one
#print axioms Ptx.SharedBarrier.Control.mark_arrival
#print axioms Ptx.SharedBarrier.Control.release
#print axioms Ptx.SharedBarrier.Control.exit
#print axioms Ptx.SharedBarrier.Control.completions_append
#print axioms Ptx.SharedBarrier.Control.step_properties
#print axioms Ptx.SharedBarrier.Control.step_preserves
#print axioms Ptx.SharedBarrier.Control.step_pc_monotone
#print axioms Ptx.SharedBarrier.Control.run_properties
#print axioms Ptx.SharedBarrier.Control.run_preserves
#print axioms Ptx.SharedBarrier.Control.completion_count
#print axioms Ptx.SharedBarrier.Control.completed_exactly_once
#print axioms Ptx.SharedBarrier.Control.arrivals_append
#print axioms Ptx.SharedBarrier.Control.step_arrival_balance
#print axioms Ptx.SharedBarrier.Control.run_arrival_balance
#print axioms Ptx.SharedBarrier.Control.all_arrived_exactly_once
#print axioms Ptx.SharedBarrier.Control.memoryCount_append
#print axioms Ptx.SharedBarrier.Control.step_memory_balance
#print axioms Ptx.SharedBarrier.Control.run_memory_balance
#print axioms Ptx.SharedBarrier.Control.step_event_control
#print axioms Ptx.SharedBarrier.Control.run_event_prefix
#print axioms Ptx.SharedBarrier.Control.load_has_completed_prefix
#print axioms Ptx.SharedBarrier.Control.arrival_has_store_prefix
#print axioms Ptx.SharedBarrier.Control.completion_all_at_barrier
#print axioms Ptx.SharedBarrier.Control.completion_has_stores_prefix
#print axioms Ptx.SharedBarrier.Control.step_halted_iff
#print axioms Ptx.SharedBarrier.Control.run_halted_iff
#print axioms Ptx.SharedBarrier.Control.halted_iff_exit_event
#print axioms Ptx.SharedBarrier.decode_encode
#print axioms Ptx.SharedBarrier.accessIndex_some
#print axioms Ptx.SharedBarrier.waiting_blocks
#print axioms Ptx.SharedBarrier.halted_blocks
#print axioms Ptx.SharedBarrier.fetched_step
#print axioms Ptx.SharedBarrier.event_origin
#print axioms Ptx.SharedBarrier.event_complete
#print axioms Ptx.SharedBarrier.dispatch_memory_safe
#print axioms Ptx.SharedBarrier.memory_safe
#print axioms Ptx.SharedBarrier.runWith_sound
#print axioms Ptx.SharedBarrier.runWith_append
#print axioms Ptx.SharedBarrierMemory.lane_index
#print axioms Ptx.SharedBarrierMemory.slot_index
#print axioms Ptx.SharedBarrierMemory.index_eta
#print axioms Ptx.SharedBarrierMemory.index_eq
#print axioms Ptx.SharedBarrierMemory.forall_index_iff
#print axioms Ptx.SharedBarrierMemory.exists_index_iff
#print axioms Ptx.SharedBarrierMemory.graph_event
#print axioms Ptx.SharedBarrierMemory.cross_iff
#print axioms Ptx.SharedBarrierMemory.source_choices
#print axioms Ptx.SharedBarrierMemory.source_after_barrier
#print axioms Ptx.SharedBarrierMemory.read_after_barrier
#print axioms Ptx.SharedBarrierMemory.fresh_valid
#print axioms Ptx.SharedBarrierMemory.stale_without_barrier
#print axioms Ptx.SharedBarrierMemory.stale_with_barrier_invalid
#print axioms Ptx.SharedBarrierMemory.fresh_phase_valid
#print axioms Ptx.SharedBarrierMemory.read_after_phase
#print axioms Ptx.SharedBarrierMemory.partner64_other
#print axioms Ptx.SharedBarrierMemory.partner64_other_warp
#print axioms Ptx.SharedBarrierMemory.partner64_involution
#print axioms Ptx.SharedBarrierMemory.two_warp_graphs
#print axioms Ptx.SharedBarrier.slotAddress_toNat
#print axioms Ptx.SharedBarrier.accessIndex_slot
#print axioms Ptx.SharedBarrier.prefixMap_zero
#print axioms Ptx.SharedBarrier.prefixMap_full
#print axioms Ptx.SharedBarrier.update_prefixMap
#print axioms Ptx.SharedBarrier.store_stage_step
#print axioms Ptx.SharedBarrier.read_stage_step
#print axioms Ptx.SharedBarrier.exit_stage_step
#print axioms Ptx.SharedBarrier.barrier_stage_step
#print axioms Ptx.SharedBarrier.prefixSchedule_length
#print axioms Ptx.SharedBarrier.schedule_length
#print axioms Ptx.SharedBarrier.run_stage
#print axioms Ptx.SharedBarrier.flatMap_singleton
#print axioms Ptx.SharedBarrier.store_execution
#print axioms Ptx.SharedBarrier.barrier_execution
#print axioms Ptx.SharedBarrier.read_execution
#print axioms Ptx.SharedBarrier.exit_execution
#print axioms Ptx.SharedBarrier.barrier_trace_prefix
#print axioms Ptx.SharedBarrier.store_start
#print axioms Ptx.SharedBarrier.store_to_barrier
#print axioms Ptx.SharedBarrier.barrier_to_read
#print axioms Ptx.SharedBarrier.read_to_exit
#print axioms Ptx.SharedBarrier.canonical_execution
#print axioms Ptx.SharedBarrier.fullSchedule_length
#print axioms Ptx.SharedBarrier.canonical_trace_length
#print axioms Ptx.SharedBarrier.candidate_completed
#print axioms Ptx.SharedBarrier.concrete_completed
#print axioms Ptx.SharedBarrier.prefixSchedule_eq_take
#print axioms Ptx.SharedBarrier.schedule_eq_finRange
#print axioms Ptx.SharedBarrier.schedule_contains
#print axioms Ptx.SharedBarrier.schedule_nodup
#print axioms Ptx.SharedBarrier.schedule_map_eq_ofFn
#print axioms Ptx.Scalar.IntegerBitCount.unary_exec
#print axioms Ptx.Scalar.IntegerBitCount.unary_false
#print axioms Ptx.Scalar.IntegerBitCount.unary_preserves_other
#print axioms Ptx.Scalar.IntegerBitCount.takeWhile_length_le
#print axioms Ptx.Scalar.IntegerBitCount.takeWhile_length_eq_iff
#print axioms Ptx.Scalar.IntegerBitCount.popc_toNat
#print axioms Ptx.Scalar.IntegerBitCount.clz_toNat
#print axioms Ptx.Scalar.IntegerBitCount.popc_bound
#print axioms Ptx.Scalar.IntegerBitCount.clz_bound
#print axioms Ptx.Scalar.IntegerBitCount.popc_zero_iff
#print axioms Ptx.Scalar.IntegerBitCount.clz_width_iff
#print axioms Ptx.Scalar.unary_exec
#print axioms Ptx.Scalar.unary_false
#print axioms Ptx.Scalar.unary_preserves_other
#print axioms Ptx.Scalar.UnaryOp.eval
#print axioms Ptx.SharedBarrier.completed_cross_origin
#print axioms Ptx.SharedBarrier.History.load_path_general

#print axioms Ptx.AffineMemory.Index
#print axioms Ptx.AffineMemory.initIndex
#print axioms Ptx.AffineMemory.programIndex
#print axioms Ptx.AffineMemory.index_cases
#print axioms Ptx.AffineMemory.programEvent
#print axioms Ptx.AffineMemory.event
#print axioms Ptx.AffineMemory.event_init
#print axioms Ptx.AffineMemory.event_program
#print axioms Ptx.AffineMemory.graph
#print axioms Ptx.AffineMemory.initialReads
#print axioms Ptx.AffineMemory.witnessSource
#print axioms Ptx.AffineMemory.witnessCo
#print axioms Ptx.AffineMemory.witness
#print axioms Ptx.AffineMemory.upper
#print axioms Ptx.AffineMemory.init_program_ne
#print axioms Ptx.AffineMemory.program_init_ne
#print axioms Ptx.AffineMemory.initIndex_inj
#print axioms Ptx.AffineMemory.programIndex_inj
#print axioms Ptx.AffineMemory.witness_no_observation
#print axioms Ptx.AffineMemory.witness_valid
#print axioms Ptx.AffineMemory.event_read
#print axioms Ptx.AffineMemory.source_initial_of_before_store
#print axioms Ptx.AffineMemory.valid_reads_initial
#print axioms Ptx.AffineMemory.witness_grounding_rank
#print axioms Ptx.AffineMemory.witness_grounding_acyclic
#print axioms Ptx.AffineMemory.wordIndex
#print axioms Ptx.AffineMemory.wordIndex_bytes
#print axioms Ptx.AffineMemory.witnessAt
#print axioms Ptx.AffineMemory.witnessAt_valid
#print axioms Ptx.AffineMemory.all_alias_example

-- Serialized logical storage, including lifetime and reallocation rejection.
#print axioms Ptx.SequentialStorage.Cell
#print axioms Ptx.SequentialStorage.Store
#print axioms Ptx.SequentialStorage.empty
#print axioms Ptx.SequentialStorage.live_lt
#print axioms Ptx.SequentialStorage.reserve
#print axioms Ptx.SequentialStorage.release
#print axioms Ptx.SequentialStorage.writeback
#print axioms Ptx.SequentialStorage.reserve_id
#print axioms Ptx.SequentialStorage.reserve_counter
#print axioms Ptx.SequentialStorage.reserve_contents
#print axioms Ptx.SequentialStorage.reserve_fresh
#print axioms Ptx.SequentialStorage.reserve_other
#print axioms Ptx.SequentialStorage.release_iff
#print axioms Ptx.SequentialStorage.writeback_properties
#print axioms Ptx.SequentialStorage.writeback_exists
#print axioms Ptx.SequentialStorage.release_absent
#print axioms Ptx.SequentialStorage.writeback_absent
#print axioms Ptx.SequentialStorage.Step
#print axioms Ptx.SequentialStorage.History
#print axioms Ptx.SequentialStorage.Step.counter_mono
#print axioms Ptx.SequentialStorage.Step.old_absent
#print axioms Ptx.SequentialStorage.History.old_absent
#print axioms Ptx.SequentialStorage.released_never_live
#print axioms Ptx.SequentialStorage.Cell.allocation
#print axioms Ptx.SequentialStorage.environment
#print axioms Ptx.SequentialStorage.address
#print axioms Ptx.SequentialStorage.access_absent
#print axioms Ptx.SequentialStorage.access_iff
#print axioms Ptx.SequentialStorage.released_access_fails
#print axioms Ptx.SequentialStorage.release_exists
#print axioms Ptx.SequentialStorage.writeback_wrong_extent
#print axioms Ptx.SequentialStorage.History.counter_mono
#print axioms Ptx.SequentialStorage.History.append
#print axioms Ptx.SequentialStorage.released_reallocated
#print axioms Ptx.SequentialStorage.writeback_environment
#print axioms Ptx.SequentialStorage.reallocation_example
#print axioms Ptx.SequentialStorage.resize_rejected
#print axioms Ptx.SequentialStorage.foreign_device_rejected

/-! Reusable pure instruction-family mechanism. -/
#print axioms Ptx.Scalar.Pure32.OperandPred
#print axioms Ptx.Scalar.Pure32.OperandPred.eval
#print axioms Ptx.Scalar.Pure32.OperandPred.reads
#print axioms Ptx.Scalar.Pure32.predicate_positive
#print axioms Ptx.Scalar.Pure32.predicate_negative
#print axioms Ptx.Scalar.Pure32.Family
#print axioms Ptx.Scalar.Pure32.Family.ofFunction
#print axioms Ptx.Scalar.Pure32.Family.ofFunction_results
#print axioms Ptx.Scalar.Pure32.Instr
#print axioms Ptx.Scalar.Pure32.Instr.wordValues
#print axioms Ptx.Scalar.Pure32.Instr.predicateValues
#print axioms Ptx.Scalar.Pure32.Instr.sourceReads
#print axioms Ptx.Scalar.Pure32.Instr.sourceReads_word
#print axioms Ptx.Scalar.Pure32.Instr.sourceReads_predicate
#print axioms Ptx.Scalar.Pure32.Occurrence
#print axioms Ptx.Scalar.Pure32.occurrence
#print axioms Ptx.Scalar.Pure32.write
#print axioms Ptx.Scalar.Pure32.Eval
#print axioms Ptx.Scalar.Pure32.Step
#print axioms Ptx.Scalar.Pure32.eval_true_iff
#print axioms Ptx.Scalar.Pure32.eval_false_iff
#print axioms Ptx.Scalar.Pure32.eval_destination
#print axioms Ptx.Scalar.Pure32.eval_frame
#print axioms Ptx.Scalar.Pure32.eval_other
#print axioms Ptx.Scalar.Pure32.eval_event
#print axioms Ptx.Scalar.Pure32.eval_reads
#print axioms Ptx.Scalar.Pure32.eval_writes
#print axioms Ptx.Scalar.Pure32.eval_no_memory
#print axioms Ptx.Scalar.Pure32.eval_alias_read
#print axioms Ptx.Scalar.Pure32.repeated_word_values
#print axioms Ptx.Scalar.Pure32.eval_positive_guard
#print axioms Ptx.Scalar.Pure32.eval_negative_guard
#print axioms Ptx.Scalar.Pure32.skip_positive_guard
#print axioms Ptx.Scalar.Pure32.skip_negative_guard
#print axioms Ptx.Scalar.Pure32.eval_exists
#print axioms Ptx.Scalar.Pure32.eval_deterministic
#print axioms Ptx.Scalar.Pure32.eval_preserves_choices
#print axioms Ptx.Scalar.Pure32.step_origin
#print axioms Ptx.Scalar.Pure32.step_iff_of_fetch
#print axioms Ptx.Scalar.Pure32.step_frame
#print axioms Ptx.Scalar.Pure32.step_false_iff
#print axioms Ptx.Scalar.Pure32.step_exists
#print axioms Ptx.Scalar.Pure32.step_no_fetch
#print axioms Ptx.Scalar.Pure32.step_unsupported
#print axioms Ptx.Scalar.Pure32.step_wrong_instruction
#print axioms Ptx.Scalar.Pure32.step_wrong_pc

/-! Actual trace projection and graph transport. -/
#print axioms Ptx.GraphTransport.IndexEquiv
#print axioms Ptx.GraphTransport.IndexEquiv.refl
#print axioms Ptx.GraphTransport.IndexEquiv.symm
#print axioms Ptx.GraphTransport.IndexEquiv.injective
#print axioms Ptx.GraphTransport.IndexEquiv.eq_iff
#print axioms Ptx.GraphTransport.IndexEquiv.ne_iff
#print axioms Ptx.GraphTransport.IndexEquiv.forall_old
#print axioms Ptx.GraphTransport.IndexEquiv.forall_old_two
#print axioms Ptx.GraphTransport.IndexEquiv.forall_old_three
#print axioms Ptx.GraphTransport.occurrence
#print axioms Ptx.GraphTransport.transport
#print axioms Ptx.GraphTransport.order
#print axioms Ptx.GraphTransport.event_thread
#print axioms Ptx.GraphTransport.event_position
#print axioms Ptx.GraphTransport.event_op
#print axioms Ptx.GraphTransport.event_address
#print axioms Ptx.GraphTransport.read
#print axioms Ptx.GraphTransport.write
#print axioms Ptx.GraphTransport.initial
#print axioms Ptx.GraphTransport.acquire
#print axioms Ptx.GraphTransport.release
#print axioms Ptx.GraphTransport.source
#print axioms Ptx.GraphTransport.value
#print axioms Ptx.GraphTransport.coherence
#print axioms Ptx.GraphTransport.po
#print axioms Ptx.GraphTransport.sameAddress
#print axioms Ptx.GraphTransport.rf
#print axioms Ptx.GraphTransport.morallyStrong
#print axioms Ptx.GraphTransport.observation
#print axioms Ptx.GraphTransport.releasePattern
#print axioms Ptx.GraphTransport.acquirePattern
#print axioms Ptx.GraphTransport.sync
#print axioms Ptx.GraphTransport.baseEdge
#print axioms Ptx.GraphTransport.path_map
#print axioms Ptx.GraphTransport.path_iff
#print axioms Ptx.GraphTransport.base
#print axioms Ptx.GraphTransport.proxyBase
#print axioms Ptx.GraphTransport.cause
#print axioms Ptx.GraphTransport.communication
#print axioms Ptx.GraphTransport.locationEdge
#print axioms Ptx.GraphTransport.locationPath
#print axioms Ptx.GraphTransport.sources_iff
#print axioms Ptx.GraphTransport.coherent_iff
#print axioms Ptx.GraphTransport.valid_iff
#print axioms Ptx.GraphTransport.ordered_base
#print axioms Ptx.GraphTransport.ordered_cause
#print axioms Ptx.GraphTransport.ordered_valid_iff
#print axioms Ptx.GraphTransport.renameAddresses
#print axioms Ptx.GraphTransport.reindex
#print axioms Ptx.GraphTransport.renameAddresses_valid_iff
#print axioms Ptx.GraphTransport.renameAddresses_ordered_valid_iff
#print axioms Ptx.GraphTransport.reindex_valid_iff
#print axioms Ptx.GraphTransport.reindex_ordered_valid_iff
#print axioms Ptx.TraceMemory.StorageKey
#print axioms Ptx.TraceMemory.Location
#print axioms Ptx.TraceMemory.Location.code
#print axioms Ptx.TraceMemory.Location.code_injective
#print axioms Ptx.TraceMemory.Location.code_eq_iff
#print axioms Ptx.TraceMemory.Catalogue
#print axioms Ptx.TraceMemory.Catalogue.same_storage
#print axioms Ptx.TraceMemory.Catalogue.different_storage
#print axioms Ptx.TraceMemory.AccessKind
#print axioms Ptx.TraceMemory.AccessKind.op
#print axioms Ptx.TraceMemory.Access
#print axioms Ptx.TraceMemory.Access.effect
#print axioms Ptx.TraceMemory.Projected
#print axioms Ptx.TraceMemory.label
#print axioms Ptx.TraceMemory.project
#print axioms Ptx.TraceMemory.label_eq_some_iff
#print axioms Ptx.TraceMemory.project_member_iff
#print axioms Ptx.TraceMemory.project_complete
#print axioms Ptx.TraceMemory.project_unique
#print axioms Ptx.TraceMemory.project_ordered
#print axioms Ptx.TraceMemory.project_nodup
#print axioms Ptx.TraceMemory.Projected.occurrence
#print axioms Ptx.TraceMemory.Projected.position_preserved
#print axioms Ptx.TraceMemory.Projected.value_preserved
#print axioms Ptx.TraceMemory.Projected.address_preserved
#print axioms Ptx.TraceMemory.Projected.kind_preserved
#print axioms Ptx.TraceMemory.Initial
#print axioms Ptx.TraceMemory.Initial.occurrence
#print axioms Ptx.TraceMemory.events
#print axioms Ptx.TraceMemory.graph
#print axioms Ptx.TraceMemory.graph_label
#print axioms Ptx.TraceMemory.po_iff
#print axioms Ptx.TraceMemory.same_address_iff
#print axioms Ptx.TraceMemory.events_member_iff
#print axioms Ptx.TraceMemory.identity
#print axioms Ptx.TraceMemory.events_unique
#print axioms Ptx.Scalar.Ordered.access
#print axioms Ptx.Scalar.Ordered.label_recover
#print axioms Ptx.Scalar.Ordered.projection_recover
#print axioms Ptx.Scalar.Ordered.run_projection
#print axioms Ptx.Scalar.Ordered.access_origin
#print axioms Ptx.Scalar.Ordered.access_complete
#print axioms Ptx.Scalar.Ordered.run_access_complete
#print axioms Ptx.Scalar.Ordered.run_project_complete
#print axioms Ptx.Scalar.ComputedPublication.Projected.initialWords
#print axioms Ptx.Scalar.ComputedPublication.Projected.events
#print axioms Ptx.Scalar.ComputedPublication.Projected.events_unique
#print axioms Ptx.Scalar.ComputedPublication.Projected.events_recover
#print axioms Ptx.Scalar.ComputedPublication.Projected.graph
#print axioms Ptx.Scalar.ComputedPublication.Projected.graph_recover
#print axioms Ptx.Scalar.ComputedPublication.Projected.publication
#print axioms Ptx.Scalar.ComputedPublication.Projected.successful_witness
#print axioms Ptx.Scalar.ComputedPublication.Projected.relaxed_witness
#print axioms Ptx.Scalar.ComputedPublication.Projected.memory_safe

#print axioms Ptx.Scalar.Select32.Eval
#print axioms Ptx.Scalar.Select32.Instr
#print axioms Ptx.Scalar.Select32.Occurrence
#print axioms Ptx.Scalar.Select32.Operation
#print axioms Ptx.Scalar.Select32.Step
#print axioms Ptx.Scalar.Select32.SupportedTarget
#print axioms Ptx.Scalar.Select32.Text.decode
#print axioms Ptx.Scalar.Select32.Text.decode_encode
#print axioms Ptx.Scalar.Select32.Text.decode_iff
#print axioms Ptx.Scalar.Select32.Text.encode
#print axioms Ptx.Scalar.Select32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Select32.compute
#print axioms Ptx.Scalar.Select32.compute_eq
#print axioms Ptx.Scalar.Select32.eval_destination
#print axioms Ptx.Scalar.Select32.eval_deterministic
#print axioms Ptx.Scalar.Select32.eval_event
#print axioms Ptx.Scalar.Select32.eval_exists
#print axioms Ptx.Scalar.Select32.eval_false_iff
#print axioms Ptx.Scalar.Select32.eval_frame
#print axioms Ptx.Scalar.Select32.eval_other
#print axioms Ptx.Scalar.Select32.eval_true_iff
#print axioms Ptx.Scalar.Select32.family
#print axioms Ptx.Scalar.Select32.lower
#print axioms Ptx.Scalar.Select32.lower_fields
#print axioms Ptx.Scalar.Select32.lower_predicate
#print axioms Ptx.Scalar.Select32.occurrence
#print axioms Ptx.Scalar.Select32.result
#print axioms Ptx.Scalar.Select32.results_iff
#print axioms Ptx.Scalar.Select32.step_exists
#print axioms Ptx.Scalar.Select32.step_no_fetch
#print axioms Ptx.Scalar.Select32.step_origin
#print axioms Ptx.Scalar.Select32.step_unsupported_target

#print axioms Ptx.Scalar.SignedMinMax32.Eval
#print axioms Ptx.Scalar.SignedMinMax32.Instr
#print axioms Ptx.Scalar.SignedMinMax32.Occurrence
#print axioms Ptx.Scalar.SignedMinMax32.Operation
#print axioms Ptx.Scalar.SignedMinMax32.Step
#print axioms Ptx.Scalar.SignedMinMax32.SupportedTarget
#print axioms Ptx.Scalar.SignedMinMax32.Text.decode
#print axioms Ptx.Scalar.SignedMinMax32.Text.decode_encode
#print axioms Ptx.Scalar.SignedMinMax32.Text.decode_iff
#print axioms Ptx.Scalar.SignedMinMax32.Text.encode
#print axioms Ptx.Scalar.SignedMinMax32.Text.mnemonic
#print axioms Ptx.Scalar.SignedMinMax32.Text.supportedMnemonic
#print axioms Ptx.Scalar.SignedMinMax32.compute
#print axioms Ptx.Scalar.SignedMinMax32.compute_max
#print axioms Ptx.Scalar.SignedMinMax32.compute_min
#print axioms Ptx.Scalar.SignedMinMax32.compute_toInt
#print axioms Ptx.Scalar.SignedMinMax32.eval_destination
#print axioms Ptx.Scalar.SignedMinMax32.eval_deterministic
#print axioms Ptx.Scalar.SignedMinMax32.eval_event
#print axioms Ptx.Scalar.SignedMinMax32.eval_exists
#print axioms Ptx.Scalar.SignedMinMax32.eval_false_iff
#print axioms Ptx.Scalar.SignedMinMax32.eval_frame
#print axioms Ptx.Scalar.SignedMinMax32.eval_other
#print axioms Ptx.Scalar.SignedMinMax32.eval_true_iff
#print axioms Ptx.Scalar.SignedMinMax32.family
#print axioms Ptx.Scalar.SignedMinMax32.lower
#print axioms Ptx.Scalar.SignedMinMax32.lower_fields
#print axioms Ptx.Scalar.SignedMinMax32.lower_operation
#print axioms Ptx.Scalar.SignedMinMax32.occurrence
#print axioms Ptx.Scalar.SignedMinMax32.result
#print axioms Ptx.Scalar.SignedMinMax32.results_iff
#print axioms Ptx.Scalar.SignedMinMax32.step_exists
#print axioms Ptx.Scalar.SignedMinMax32.step_no_fetch
#print axioms Ptx.Scalar.SignedMinMax32.step_origin
#print axioms Ptx.Scalar.SignedMinMax32.step_unsupported_target

/-! Fetched shared reduction: all public definitions and proofs, including universal
output/storage, memory admission, constructed existence and access safety. -/
#print axioms Ptx.Scalar.SharedReduction.Block
#print axioms Ptx.Scalar.SharedReduction.Block.memoryForm
#print axioms Ptx.Scalar.SharedReduction.Block.project
#print axioms Ptx.Scalar.SharedReduction.Block.scope
#print axioms Ptx.Scalar.SharedReduction.Config
#print axioms Ptx.Scalar.SharedReduction.Correctness.candidate_output
#print axioms Ptx.Scalar.SharedReduction.Correctness.completed_candidate
#print axioms Ptx.Scalar.SharedReduction.Correctness.completed_execution
#print axioms Ptx.Scalar.SharedReduction.Correctness.emitted_access_safe
#print axioms Ptx.Scalar.SharedReduction.Correctness.read_contract
#print axioms Ptx.Scalar.SharedReduction.Machine.Access
#print axioms Ptx.Scalar.SharedReduction.Machine.Block
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.AtBarrier
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.Invariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.SupportedTarget
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.eval_effect_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.fetch_sync
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.fetched_classification
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.fetched_global_store
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.form
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.forms_eligible
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.memoryKind
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.reachable_release
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.release_all_at_barrier
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.runWith_global_store_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.runWith_memory_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.runWith_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.scalar_effect_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.step_global_store_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.step_memory_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.step_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Control.waiting_step_unchanged
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.Invariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.LaneInvariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.LaneValueInvariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.Recorded
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.ValueInvariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.reachable
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.reachable_shared_store_recorded
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.recorded_append
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.release_lane_fields
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.runWith_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.runWith_producer_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.runWith_shared_store_path
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.runWith_shared_store_recorded
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.shared_store_path
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.step_other
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.step_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.step_producer_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.step_shared_store_recorded
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.value_extend
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.value_initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.value_reachable
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.value_runWith_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Data.value_step_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Event
#print axioms Ptx.Scalar.SharedReduction.Machine.Execution
#print axioms Ptx.Scalar.SharedReduction.Machine.History.arrivalCredit
#print axioms Ptx.Scalar.SharedReduction.Machine.History.arrival_has_store_prefix
#print axioms Ptx.Scalar.SharedReduction.Machine.History.arrival_member
#print axioms Ptx.Scalar.SharedReduction.Machine.History.arrival_path
#print axioms Ptx.Scalar.SharedReduction.Machine.History.arrivals
#print axioms Ptx.Scalar.SharedReduction.Machine.History.arrivals_append
#print axioms Ptx.Scalar.SharedReduction.Machine.History.barrier_key
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completing_events
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completion_at_most_once
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completion_count
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completion_has_stores_prefix
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completion_member
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completion_path
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completions
#print axioms Ptx.Scalar.SharedReduction.Machine.History.completions_append
#print axioms Ptx.Scalar.SharedReduction.Machine.History.credit_bound
#print axioms Ptx.Scalar.SharedReduction.Machine.History.generation_at_barrier
#print axioms Ptx.Scalar.SharedReduction.Machine.History.generation_count
#print axioms Ptx.Scalar.SharedReduction.Machine.History.isCompletion
#print axioms Ptx.Scalar.SharedReduction.Machine.History.isPublication
#print axioms Ptx.Scalar.SharedReduction.Machine.History.isPublication_iff
#print axioms Ptx.Scalar.SharedReduction.Machine.History.load_has_completed_prefix
#print axioms Ptx.Scalar.SharedReduction.Machine.History.load_path
#print axioms Ptx.Scalar.SharedReduction.Machine.History.load_prefix_at_index
#print axioms Ptx.Scalar.SharedReduction.Machine.History.phaseCredit
#print axioms Ptx.Scalar.SharedReduction.Machine.History.phaseKey
#print axioms Ptx.Scalar.SharedReduction.Machine.History.phase_progress
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publicationCredit
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publication_at_most_once
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publication_count
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publication_member
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publication_progress
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publications
#print axioms Ptx.Scalar.SharedReduction.Machine.History.publications_append
#print axioms Ptx.Scalar.SharedReduction.Machine.History.run_arrival_balance
#print axioms Ptx.Scalar.SharedReduction.Machine.History.run_event_prefix
#print axioms Ptx.Scalar.SharedReduction.Machine.History.run_index_prefix
#print axioms Ptx.Scalar.SharedReduction.Machine.History.run_phase_balance
#print axioms Ptx.Scalar.SharedReduction.Machine.History.run_publication_balance
#print axioms Ptx.Scalar.SharedReduction.Machine.History.step_arrival_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.History.step_barrier_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.History.step_shared_load_loop
#print axioms Ptx.Scalar.SharedReduction.Machine.Instruction
#print axioms Ptx.Scalar.SharedReduction.Machine.Label
#print axioms Ptx.Scalar.SharedReduction.Machine.Lane
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.Invariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.LaneInvariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.TerminalInvariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.TerminalLane
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.halted_leader
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.load_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.progress
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.reachable
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.reachable_shared_load_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.remaining
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.runWith_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.runWith_shared_load_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.step_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.step_shared_load_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.terminal_initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.terminal_reachable
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.terminal_runWith
#print axioms Ptx.Scalar.SharedReduction.Machine.Loop.terminal_step
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.SerialCertificate
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.SerialCertificate.grounded
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.SerialCertificate.valid
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.access
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.accessRank
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.access_complete
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.access_fields
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.access_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrierOrder
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_base
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_cause
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_excludes_initial_source
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_order_acyclic
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_order_increases
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_order_noninitial
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.barrier_unique_source
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.bytePointer_word
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.byte_recover
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonicalTrace
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_access_exists
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_accesses_ordered
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_base_before
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_global_initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_initial_before
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_memory_classification
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_position_injective
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_program_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_program_rank
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_rank_increases
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_rank_injective
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_read
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_shared_latest
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_source_exists
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_valid_exists
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.canonical_write
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.catalogue
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.count_at_most_one_position
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.effectRank
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.effect_rank_recover
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.eventRank
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.extra
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.global_input_read
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.graph
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.graph_identity_injective
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.graph_initial_iff
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.grounding
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_event_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_global
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_global_member
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_index
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_rank_bound
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_shared
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.initial_unique
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.kindMatches
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.kindMatches_iff
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.labels
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.labels_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.labels_unique
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.location
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.ofEffect
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.ofEffect_pointer
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.program_global_write_address
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.program_write_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.projection
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.projection_complete
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.projection_ordered
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.projection_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.projection_unique
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.rankBase
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.runGraph
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.runLabels
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_access_complete
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_access_iff_raw
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_global_input_read
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_global_load_value
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_graph_complete
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_projection_complete
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_shared_load_member_value
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_shared_load_value
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_shared_source
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_shared_store_before
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_shared_write_slot
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.run_shared_write_unique
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.slot
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.source_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.spaces_distinct
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.sublist_positions
#print axioms Ptx.Scalar.SharedReduction.Machine.Memory.triple_earlier_positions
#print axioms Ptx.Scalar.SharedReduction.Machine.Ready
#print axioms Ptx.Scalar.SharedReduction.Machine.Result
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.Invariant
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.LaneInvariant
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.ReadContract
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.Shape
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.global_store_sum
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.initial
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.observed_value
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.progress
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.reachable
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.readContract_append
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.runWith_global_store_sum
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.runWith_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.shape_of_loop
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.step_global_store_sum
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.step_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.ResultProof.total_succ
#print axioms Ptx.Scalar.SharedReduction.Machine.Runs
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.arena
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.run_lengths
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.run_memory_safe
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.scalar_lengths
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.scalar_memory_safe
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.step_lengths
#print axioms Ptx.Scalar.SharedReduction.Machine.Safety.step_memory_safe
#print axioms Ptx.Scalar.SharedReduction.Machine.State
#print axioms Ptx.Scalar.SharedReduction.Machine.Status
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.Invariant
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.halted_leader
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.initial
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.output_reached
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.reachable
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.runWith_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.Writeback.step_preserves
#print axioms Ptx.Scalar.SharedReduction.Machine.accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.accesses_append
#print axioms Ptx.Scalar.SharedReduction.Machine.barrierConfig
#print axioms Ptx.Scalar.SharedReduction.Machine.barrierRequest
#print axioms Ptx.Scalar.SharedReduction.Machine.barrierStage
#print axioms Ptx.Scalar.SharedReduction.Machine.barrier_prefix
#print axioms Ptx.Scalar.SharedReduction.Machine.barrier_prefix_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.barrier_round
#print axioms Ptx.Scalar.SharedReduction.Machine.barrier_round_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.barrier_stage_step
#print axioms Ptx.Scalar.SharedReduction.Machine.dispatch
#print axioms Ptx.Scalar.SharedReduction.Machine.follower_exit
#print axioms Ptx.Scalar.SharedReduction.Machine.follower_no_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.followers
#print axioms Ptx.Scalar.SharedReduction.Machine.followers_no_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.followers_phase
#print axioms Ptx.Scalar.SharedReduction.Machine.fullSchedule
#print axioms Ptx.Scalar.SharedReduction.Machine.full_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.full_execution
#print axioms Ptx.Scalar.SharedReduction.Machine.initialize_no_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.leader_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.leader_initialize
#print axioms Ptx.Scalar.SharedReduction.Machine.leader_phase
#print axioms Ptx.Scalar.SharedReduction.Machine.loopAccesses
#print axioms Ptx.Scalar.SharedReduction.Machine.loopNext
#print axioms Ptx.Scalar.SharedReduction.Machine.loop_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.loop_execution
#print axioms Ptx.Scalar.SharedReduction.Machine.loop_seven
#print axioms Ptx.Scalar.SharedReduction.Machine.loop_seven_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.loop_zero
#print axioms Ptx.Scalar.SharedReduction.Machine.loop_zero_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.memoryEvent
#print axioms Ptx.Scalar.SharedReduction.Machine.output_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.output_phase
#print axioms Ptx.Scalar.SharedReduction.Machine.producerAccesses
#print axioms Ptx.Scalar.SharedReduction.Machine.producerSchedule
#print axioms Ptx.Scalar.SharedReduction.Machine.producer_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.producer_list
#print axioms Ptx.Scalar.SharedReduction.Machine.producer_list_accesses
#print axioms Ptx.Scalar.SharedReduction.Machine.producer_phase
#print axioms Ptx.Scalar.SharedReduction.Machine.producer_round
#print axioms Ptx.Scalar.SharedReduction.Machine.program
#print axioms Ptx.Scalar.SharedReduction.Machine.resumed
#print axioms Ptx.Scalar.SharedReduction.Machine.run
#print axioms Ptx.Scalar.SharedReduction.Machine.runWith
#print axioms Ptx.Scalar.SharedReduction.Machine.run_append
#print axioms Ptx.Scalar.SharedReduction.Machine.run_sound
#print axioms Ptx.Scalar.SharedReduction.Machine.scalarStep
#print axioms Ptx.Scalar.SharedReduction.Machine.setLane
#print axioms Ptx.Scalar.SharedReduction.Machine.setLane_other
#print axioms Ptx.Scalar.SharedReduction.Machine.setLane_same
#print axioms Ptx.Scalar.SharedReduction.Machine.start
#print axioms Ptx.Scalar.SharedReduction.Machine.step
#print axioms Ptx.Scalar.SharedReduction.Machine.step_origin
#print axioms Ptx.Scalar.SharedReduction.Machine.sync_no_accesses
#print axioms Ptx.Scalar.SharedReduction.Seed
#print axioms Ptx.Scalar.SharedReduction.Space
#print axioms Ptx.Scalar.SharedReduction.barrierConfig
#print axioms Ptx.Scalar.SharedReduction.barrier_round_exists
#print axioms Ptx.Scalar.SharedReduction.bytePointer
#print axioms Ptx.Scalar.SharedReduction.halted_unique
#print axioms Ptx.Scalar.SharedReduction.leader
#print axioms Ptx.Scalar.SharedReduction.leaderBlock
#print axioms Ptx.Scalar.SharedReduction.leaderProgram
#print axioms Ptx.Scalar.SharedReduction.leaderStart
#print axioms Ptx.Scalar.SharedReduction.leader_any_completed
#print axioms Ptx.Scalar.SharedReduction.leader_correct
#print axioms Ptx.Scalar.SharedReduction.leader_environment_safe
#print axioms Ptx.Scalar.SharedReduction.leader_execution
#print axioms Ptx.Scalar.SharedReduction.leader_safe
#print axioms Ptx.Scalar.SharedReduction.oneWarp
#print axioms Ptx.Scalar.SharedReduction.output
#print axioms Ptx.Scalar.SharedReduction.outputBlock
#print axioms Ptx.Scalar.SharedReduction.outputProgram
#print axioms Ptx.Scalar.SharedReduction.outputStart
#print axioms Ptx.Scalar.SharedReduction.output_correct
#print axioms Ptx.Scalar.SharedReduction.output_execution
#print axioms Ptx.Scalar.SharedReduction.output_safe
#print axioms Ptx.Scalar.SharedReduction.producer
#print axioms Ptx.Scalar.SharedReduction.producerBlock
#print axioms Ptx.Scalar.SharedReduction.producerProgram
#print axioms Ptx.Scalar.SharedReduction.producerStart
#print axioms Ptx.Scalar.SharedReduction.producer_correct
#print axioms Ptx.Scalar.SharedReduction.producer_execution
#print axioms Ptx.Scalar.SharedReduction.producer_safe
#print axioms Ptx.Scalar.SharedReduction.project_complete
#print axioms Ptx.Scalar.SharedReduction.project_origin
#print axioms Ptx.Scalar.SharedReduction.publication
#print axioms Ptx.Scalar.SharedReduction.publicationBlock
#print axioms Ptx.Scalar.SharedReduction.publicationStart
#print axioms Ptx.Scalar.SharedReduction.publication_all
#print axioms Ptx.Scalar.SharedReduction.publication_correct
#print axioms Ptx.Scalar.SharedReduction.publishAll
#print axioms Ptx.Scalar.SharedReduction.publishAll_cons
#print axioms Ptx.Scalar.SharedReduction.publishAll_length
#print axioms Ptx.Scalar.SharedReduction.publishAll_lookup
#print axioms Ptx.Scalar.SharedReduction.sharedAddress
#print axioms Ptx.Scalar.SharedReduction.sharedEnvironment
#print axioms Ptx.Scalar.SharedReduction.sharedStore
#print axioms Ptx.Scalar.SharedReduction.shared_access_iff
#print axioms Ptx.Scalar.SharedReduction.staged_execution
#print axioms Ptx.Scalar.SharedReduction.total
#print axioms Ptx.Scalar.SharedReduction.total_publication
#print axioms Ptx.Scalar.SharedReduction.twoWarps
#print axioms Ptx.Scalar.Bitwise32.SupportedTarget
#print axioms Ptx.Scalar.Bitwise32.Operation
#print axioms Ptx.Scalar.Bitwise32.Instr
#print axioms Ptx.Scalar.Bitwise32.compute
#print axioms Ptx.Scalar.Bitwise32.family
#print axioms Ptx.Scalar.Bitwise32.lower
#print axioms Ptx.Scalar.Bitwise32.result
#print axioms Ptx.Scalar.Bitwise32.occurrence
#print axioms Ptx.Scalar.Bitwise32.compute_eq
#print axioms Ptx.Scalar.Bitwise32.results_iff
#print axioms Ptx.Scalar.Bitwise32.lower_operation
#print axioms Ptx.Scalar.Bitwise32.lower_fields
#print axioms Ptx.Scalar.Bitwise32.eval_true_iff
#print axioms Ptx.Scalar.Bitwise32.eval_false_iff
#print axioms Ptx.Scalar.Bitwise32.eval_destination
#print axioms Ptx.Scalar.Bitwise32.eval_frame
#print axioms Ptx.Scalar.Bitwise32.eval_other
#print axioms Ptx.Scalar.Bitwise32.eval_event
#print axioms Ptx.Scalar.Bitwise32.eval_deterministic
#print axioms Ptx.Scalar.Bitwise32.eval_exists
#print axioms Ptx.Scalar.Bitwise32.step_origin
#print axioms Ptx.Scalar.Bitwise32.step_exists
#print axioms Ptx.Scalar.Bitwise32.step_no_fetch
#print axioms Ptx.Scalar.Bitwise32.step_unsupported_target
#print axioms Ptx.Scalar.Bitwise32.Text.mnemonic
#print axioms Ptx.Scalar.Bitwise32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Bitwise32.Text.encode
#print axioms Ptx.Scalar.Bitwise32.Text.decode
#print axioms Ptx.Scalar.Bitwise32.Text.decode_encode
#print axioms Ptx.Scalar.Bitwise32.Text.decode_iff
#print axioms Ptx.Scalar.UnaryBits32.SupportedTarget
#print axioms Ptx.Scalar.UnaryBits32.Operation
#print axioms Ptx.Scalar.UnaryBits32.Instr
#print axioms Ptx.Scalar.UnaryBits32.compute
#print axioms Ptx.Scalar.UnaryBits32.family
#print axioms Ptx.Scalar.UnaryBits32.lower
#print axioms Ptx.Scalar.UnaryBits32.result
#print axioms Ptx.Scalar.UnaryBits32.occurrence
#print axioms Ptx.Scalar.UnaryBits32.compute_eq
#print axioms Ptx.Scalar.UnaryBits32.results_iff
#print axioms Ptx.Scalar.UnaryBits32.lower_operation
#print axioms Ptx.Scalar.UnaryBits32.lower_fields
#print axioms Ptx.Scalar.UnaryBits32.eval_true_iff
#print axioms Ptx.Scalar.UnaryBits32.eval_false_iff
#print axioms Ptx.Scalar.UnaryBits32.eval_destination
#print axioms Ptx.Scalar.UnaryBits32.eval_frame
#print axioms Ptx.Scalar.UnaryBits32.eval_other
#print axioms Ptx.Scalar.UnaryBits32.eval_event
#print axioms Ptx.Scalar.UnaryBits32.eval_deterministic
#print axioms Ptx.Scalar.UnaryBits32.eval_exists
#print axioms Ptx.Scalar.UnaryBits32.step_origin
#print axioms Ptx.Scalar.UnaryBits32.step_exists
#print axioms Ptx.Scalar.UnaryBits32.step_no_fetch
#print axioms Ptx.Scalar.UnaryBits32.step_unsupported_target
#print axioms Ptx.Scalar.UnaryBits32.Text.supportedMnemonic
#print axioms Ptx.Scalar.UnaryBits32.Text.mnemonic
#print axioms Ptx.Scalar.UnaryBits32.Text.encode
#print axioms Ptx.Scalar.UnaryBits32.Text.decode
#print axioms Ptx.Scalar.UnaryBits32.Text.decode_encode
#print axioms Ptx.Scalar.UnaryBits32.Text.decode_iff

-- Catalog composition, complete kernel and delegated shifts.
#print axioms Ptx.Scalar.Mixed.Path.append
#print axioms Ptx.Scalar.Mixed.Path.invariant
#print axioms Ptx.Scalar.Mixed.Path.event_origin
#print axioms Ptx.Scalar.PureKernel.Event.memory
#print axioms Ptx.Scalar.PureKernel.Event.pc
#print axioms Ptx.Scalar.PureKernel.Event.instruction
#print axioms Ptx.Scalar.PureKernel.liftScalar
#print axioms Ptx.Scalar.PureKernel.Eligible
#print axioms Ptx.Scalar.PureKernel.Instr.Supported
#print axioms Ptx.Scalar.PureKernel.Dispatch
#print axioms Ptx.Scalar.PureKernel.eval_scalar_iff
#print axioms Ptx.Scalar.PureKernel.eval_pure_iff
#print axioms Ptx.Scalar.PureKernel.dispatch_fetch
#print axioms Ptx.Scalar.PureKernel.dispatch_unsupported
#print axioms Ptx.Scalar.PureKernel.dispatch_ineligible
#print axioms Ptx.Scalar.PureKernel.dispatch_exists
#print axioms Ptx.Scalar.PureKernel.dispatch_success_eval
#print axioms Ptx.Scalar.PureKernel.Advances
#print axioms Ptx.Scalar.PureKernel.Run.not_exhausted
#print axioms Ptx.Scalar.PureKernel.scalar_next_iff
#print axioms Ptx.Scalar.PureKernel.scalar_halted_iff
#print axioms Ptx.Scalar.PureKernel.eval_event_origin
#print axioms Ptx.Scalar.PureKernel.dispatch_event_origin
#print axioms Ptx.Scalar.PureKernel.eval_next_safe
#print axioms Ptx.Scalar.PureKernel.eval_halted
#print axioms Ptx.Scalar.PureKernel.dispatch_next_safe
#print axioms Ptx.Scalar.PureKernel.dispatch_halted
#print axioms Ptx.Scalar.PureKernel.path_memory_length
#print axioms Ptx.Scalar.PureKernel.path_memory_safe
#print axioms Ptx.Scalar.PureKernel.Run.memory_length
#print axioms Ptx.Scalar.PureKernel.Run.memory_safe
#print axioms Ptx.Scalar.PureKernel.StoresTo
#print axioms Ptx.Scalar.PureKernel.eval_frame
#print axioms Ptx.Scalar.PureKernel.dispatch_frame
#print axioms Ptx.Scalar.PureKernel.path_frame
#print axioms Ptx.Scalar.PureKernel.Run.frame
#print axioms Ptx.Scalar.PureKernel.Run.unfold
#print axioms Ptx.Scalar.PureKernel.eval_pure_next_iff
#print axioms Ptx.Scalar.PureKernel.dispatch_pure_iff
#print axioms Ptx.Scalar.PureKernel.dispatch_preserves_choices
#print axioms Ptx.Scalar.PureKernel.Functional
#print axioms Ptx.Scalar.PureKernel.eval_deterministic
#print axioms Ptx.Scalar.PureKernel.dispatch_deterministic
#print axioms Ptx.Scalar.PureKernel.Run.deterministic
#print axioms Ptx.Scalar.ReviewedPure.Operation
#print axioms Ptx.Scalar.ReviewedPure.family
#print axioms Ptx.Scalar.ReviewedPure.catalog
#print axioms Ptx.Scalar.ReviewedPure.bitwise
#print axioms Ptx.Scalar.ReviewedPure.unary
#print axioms Ptx.Scalar.ReviewedPure.select
#print axioms Ptx.Scalar.ReviewedPure.signedMinMax
#print axioms Ptx.Scalar.ReviewedPure.shift
#print axioms Ptx.Scalar.ReviewedPure.functional
#print axioms Ptx.Scalar.ReviewedPure.scalarBitwise
#print axioms Ptx.Scalar.ReviewedPure.bitwise_result_agrees
#print axioms Ptx.Scalar.ReviewedPure.bitwise_scalar_step
#print axioms Ptx.Scalar.ReviewedPure.bitwise_scalar_iff
#print axioms Ptx.Scalar.ReviewedPure.bitwise_event_agrees
#print axioms Ptx.Scalar.ReviewedPure.shift_left_agrees
#print axioms Ptx.Scalar.ReviewedPure.shift_right_agrees
#print axioms Ptx.Scalar.MaskSelect.answer
#print axioms Ptx.Scalar.MaskSelect.loadX
#print axioms Ptx.Scalar.MaskSelect.loadY
#print axioms Ptx.Scalar.MaskSelect.maskI
#print axioms Ptx.Scalar.MaskSelect.compareI
#print axioms Ptx.Scalar.MaskSelect.selectI
#print axioms Ptx.Scalar.MaskSelect.storeI
#print axioms Ptx.Scalar.MaskSelect.exitI
#print axioms Ptx.Scalar.MaskSelect.program
#print axioms Ptx.Scalar.MaskSelect.initial
#print axioms Ptx.Scalar.MaskSelect.s1
#print axioms Ptx.Scalar.MaskSelect.s2
#print axioms Ptx.Scalar.MaskSelect.s3
#print axioms Ptx.Scalar.MaskSelect.s4
#print axioms Ptx.Scalar.MaskSelect.s5
#print axioms Ptx.Scalar.MaskSelect.finalState
#print axioms Ptx.Scalar.MaskSelect.trace
#print axioms Ptx.Scalar.MaskSelect.execution
#print axioms Ptx.Scalar.MaskSelect.execution_exists
#print axioms Ptx.Scalar.MaskSelect.correct
#print axioms Ptx.Scalar.MaskSelect.memory_safe
#print axioms Ptx.Scalar.MaskSelect.output_correct
#print axioms Ptx.Scalar.MaskSelect.other_memory
#print axioms Ptx.Scalar.PureKernelExamples.choiceFamily
#print axioms Ptx.Scalar.PureKernelExamples.choiceCatalog
#print axioms Ptx.Scalar.PureKernelExamples.choice
#print axioms Ptx.Scalar.PureKernelExamples.start
#print axioms Ptx.Scalar.PureKernelExamples.two_outcomes
#print axioms Ptx.Scalar.PureKernelExamples.skipped_target_rejected
#print axioms Ptx.Scalar.PureKernelExamples.outside_domain
#print axioms Ptx.Scalar.PureKernelExamples.branchProgram
#print axioms Ptx.Scalar.PureKernelExamples.branch_exit
#print axioms Ptx.Scalar.PureKernelExamples.missing_pc
#print axioms Ptx.Scalar.PureKernelExamples.misaligned_load
#print axioms Ptx.Scalar.Shift32.SupportedTarget
#print axioms Ptx.Scalar.Shift32.compute
#print axioms Ptx.Scalar.Shift32.family
#print axioms Ptx.Scalar.Shift32.lower
#print axioms Ptx.Scalar.Shift32.result
#print axioms Ptx.Scalar.Shift32.occurrence
#print axioms Ptx.Scalar.Shift32.compute_eq
#print axioms Ptx.Scalar.Shift32.results_iff
#print axioms Ptx.Scalar.Shift32.lower_operation
#print axioms Ptx.Scalar.Shift32.lower_fields
#print axioms Ptx.Scalar.Shift32.eval_true_iff
#print axioms Ptx.Scalar.Shift32.eval_false_iff
#print axioms Ptx.Scalar.Shift32.eval_destination
#print axioms Ptx.Scalar.Shift32.eval_frame
#print axioms Ptx.Scalar.Shift32.eval_other
#print axioms Ptx.Scalar.Shift32.eval_event
#print axioms Ptx.Scalar.Shift32.eval_deterministic
#print axioms Ptx.Scalar.Shift32.eval_exists
#print axioms Ptx.Scalar.Shift32.step_origin
#print axioms Ptx.Scalar.Shift32.step_exists
#print axioms Ptx.Scalar.Shift32.step_no_fetch
#print axioms Ptx.Scalar.Shift32.step_unsupported_target
#print axioms Ptx.Scalar.Shift32.Text.mnemonic
#print axioms Ptx.Scalar.Shift32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Shift32.Text.encode
#print axioms Ptx.Scalar.Shift32.Text.decode
#print axioms Ptx.Scalar.Shift32.Text.decode_encode
#print axioms Ptx.Scalar.Shift32.Text.decode_iff

-- Three preflighted Luna families and catalog adapters.
#print axioms Ptx.Scalar.Brev32.SupportedTarget
#print axioms Ptx.Scalar.Brev32.compute
#print axioms Ptx.Scalar.Brev32.family
#print axioms Ptx.Scalar.Brev32.lower
#print axioms Ptx.Scalar.Brev32.result
#print axioms Ptx.Scalar.Brev32.occurrence
#print axioms Ptx.Scalar.Brev32.compute_eq
#print axioms Ptx.Scalar.Brev32.results_iff
#print axioms Ptx.Scalar.Brev32.lower_operation
#print axioms Ptx.Scalar.Brev32.lower_fields
#print axioms Ptx.Scalar.Brev32.eval_true_iff
#print axioms Ptx.Scalar.Brev32.eval_false_iff
#print axioms Ptx.Scalar.Brev32.eval_destination
#print axioms Ptx.Scalar.Brev32.eval_frame
#print axioms Ptx.Scalar.Brev32.eval_other
#print axioms Ptx.Scalar.Brev32.eval_event
#print axioms Ptx.Scalar.Brev32.eval_deterministic
#print axioms Ptx.Scalar.Brev32.eval_exists
#print axioms Ptx.Scalar.Brev32.step_origin
#print axioms Ptx.Scalar.Brev32.step_exists
#print axioms Ptx.Scalar.Brev32.step_no_fetch
#print axioms Ptx.Scalar.Brev32.step_unsupported_target
#print axioms Ptx.Scalar.Brev32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Brev32.Text.mnemonic
#print axioms Ptx.Scalar.Brev32.Text.encode
#print axioms Ptx.Scalar.Brev32.Text.decode
#print axioms Ptx.Scalar.Brev32.Text.decode_encode
#print axioms Ptx.Scalar.Brev32.Text.decode_iff
#print axioms Ptx.Scalar.MulHi32.SupportedTarget
#print axioms Ptx.Scalar.MulHi32.compute
#print axioms Ptx.Scalar.MulHi32.family
#print axioms Ptx.Scalar.MulHi32.compute_eq
#print axioms Ptx.Scalar.MulHi32.results_iff
#print axioms Ptx.Scalar.MulHi32.lower
#print axioms Ptx.Scalar.MulHi32.result
#print axioms Ptx.Scalar.MulHi32.occurrence
#print axioms Ptx.Scalar.MulHi32.lower_operation
#print axioms Ptx.Scalar.MulHi32.lower_fields
#print axioms Ptx.Scalar.MulHi32.eval_true_iff
#print axioms Ptx.Scalar.MulHi32.eval_false_iff
#print axioms Ptx.Scalar.MulHi32.eval_destination
#print axioms Ptx.Scalar.MulHi32.eval_frame
#print axioms Ptx.Scalar.MulHi32.eval_other
#print axioms Ptx.Scalar.MulHi32.eval_event
#print axioms Ptx.Scalar.MulHi32.eval_deterministic
#print axioms Ptx.Scalar.MulHi32.eval_exists
#print axioms Ptx.Scalar.MulHi32.step_origin
#print axioms Ptx.Scalar.MulHi32.step_exists
#print axioms Ptx.Scalar.MulHi32.step_no_fetch
#print axioms Ptx.Scalar.MulHi32.step_unsupported_target
#print axioms Ptx.Scalar.MulHi32.Text.supportedMnemonic
#print axioms Ptx.Scalar.MulHi32.Text.mnemonic
#print axioms Ptx.Scalar.MulHi32.Text.encode
#print axioms Ptx.Scalar.MulHi32.Text.decode
#print axioms Ptx.Scalar.MulHi32.Text.decode_encode
#print axioms Ptx.Scalar.MulHi32.Text.decode_iff
#print axioms Ptx.Scalar.Bfe32.SupportedTarget
#print axioms Ptx.Scalar.Bfe32.compute
#print axioms Ptx.Scalar.Bfe32.family
#print axioms Ptx.Scalar.Bfe32.lower
#print axioms Ptx.Scalar.Bfe32.result
#print axioms Ptx.Scalar.Bfe32.occurrence
#print axioms Ptx.Scalar.Bfe32.compute_eq
#print axioms Ptx.Scalar.Bfe32.results_iff
#print axioms Ptx.Scalar.Bfe32.lower_operation
#print axioms Ptx.Scalar.Bfe32.lower_fields
#print axioms Ptx.Scalar.Bfe32.eval_true_iff
#print axioms Ptx.Scalar.Bfe32.eval_false_iff
#print axioms Ptx.Scalar.Bfe32.eval_destination
#print axioms Ptx.Scalar.Bfe32.eval_frame
#print axioms Ptx.Scalar.Bfe32.eval_other
#print axioms Ptx.Scalar.Bfe32.eval_event
#print axioms Ptx.Scalar.Bfe32.eval_deterministic
#print axioms Ptx.Scalar.Bfe32.eval_exists
#print axioms Ptx.Scalar.Bfe32.step_origin
#print axioms Ptx.Scalar.Bfe32.step_exists
#print axioms Ptx.Scalar.Bfe32.step_no_fetch
#print axioms Ptx.Scalar.Bfe32.step_unsupported_target
#print axioms Ptx.Scalar.Bfe32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Bfe32.Text.mnemonic
#print axioms Ptx.Scalar.Bfe32.Text.encode
#print axioms Ptx.Scalar.Bfe32.Text.decode
#print axioms Ptx.Scalar.Bfe32.Text.decode_encode
#print axioms Ptx.Scalar.Bfe32.Text.decode_iff
#print axioms Ptx.Scalar.ReviewedPure.brev
#print axioms Ptx.Scalar.ReviewedPure.mulHi
#print axioms Ptx.Scalar.ReviewedPure.bfe

/-! Array loop and reusable deterministic termination rules. -/
#print axioms Ptx.Scalar.PureKernel.Run.prepend
#print axioms Ptx.Scalar.PureKernel.Run.complete_prefix
#print axioms Ptx.Scalar.PureKernel.Run.no_infinite_advances
#print axioms Ptx.Scalar.ArrayMaskSelect.transform
#print axioms Ptx.Scalar.ArrayMaskSelect.pointer
#print axioms Ptx.Scalar.ArrayMaskSelect.testI
#print axioms Ptx.Scalar.ArrayMaskSelect.doneI
#print axioms Ptx.Scalar.ArrayMaskSelect.loadI
#print axioms Ptx.Scalar.ArrayMaskSelect.selectI
#print axioms Ptx.Scalar.ArrayMaskSelect.storeI
#print axioms Ptx.Scalar.ArrayMaskSelect.incrementI
#print axioms Ptx.Scalar.ArrayMaskSelect.decrementI
#print axioms Ptx.Scalar.ArrayMaskSelect.backI
#print axioms Ptx.Scalar.ArrayMaskSelect.program
#print axioms Ptx.Scalar.ArrayMaskSelect.initial
#print axioms Ptx.Scalar.ArrayMaskSelect.Bounds
#print axioms Ptx.Scalar.ArrayMaskSelect.iteration
#print axioms Ptx.Scalar.ArrayMaskSelect.empty_execution
#print axioms Ptx.Scalar.ArrayMaskSelect.execution
#print axioms Ptx.Scalar.ArrayMaskSelect.correct
#print axioms Ptx.Scalar.ArrayMaskSelect.prefix_termination
#print axioms Ptx.Scalar.ArrayMaskSelect.no_infinite_execution
#print axioms Ptx.Scalar.ArrayMaskSelect.memory_safe
#print axioms Ptx.Scalar.ArrayMaskSelect.completed_memory_safe
#print axioms Ptx.Scalar.ArrayMaskSelect.other_memory

/-! Reviewed bit-field insertion. -/
#print axioms Ptx.Scalar.Bfi32.SupportedTarget
#print axioms Ptx.Scalar.Bfi32.compute
#print axioms Ptx.Scalar.Bfi32.family
#print axioms Ptx.Scalar.Bfi32.lower
#print axioms Ptx.Scalar.Bfi32.result
#print axioms Ptx.Scalar.Bfi32.occurrence
#print axioms Ptx.Scalar.Bfi32.compute_bit
#print axioms Ptx.Scalar.Bfi32.results_iff
#print axioms Ptx.Scalar.Bfi32.lower_operation
#print axioms Ptx.Scalar.Bfi32.lower_fields
#print axioms Ptx.Scalar.Bfi32.eval_true_iff
#print axioms Ptx.Scalar.Bfi32.eval_false_iff
#print axioms Ptx.Scalar.Bfi32.eval_destination
#print axioms Ptx.Scalar.Bfi32.eval_frame
#print axioms Ptx.Scalar.Bfi32.eval_other
#print axioms Ptx.Scalar.Bfi32.eval_event
#print axioms Ptx.Scalar.Bfi32.eval_deterministic
#print axioms Ptx.Scalar.Bfi32.eval_exists
#print axioms Ptx.Scalar.Bfi32.step_origin
#print axioms Ptx.Scalar.Bfi32.step_exists
#print axioms Ptx.Scalar.Bfi32.step_no_fetch
#print axioms Ptx.Scalar.Bfi32.step_unsupported_target
#print axioms Ptx.Scalar.Bfi32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Bfi32.Text.encode
#print axioms Ptx.Scalar.Bfi32.Text.decode
#print axioms Ptx.Scalar.Bfi32.Text.decode_encode
#print axioms Ptx.Scalar.Bfi32.Text.decode_iff
#print axioms Ptx.Scalar.ReviewedPure.bfi
