import Ptx.ScalarKernels
import Ptx.Checker

/-!
# A constructive scalar-to-memory witness

Memory labels are extracted from real scalar occurrences, preserving dispatch
positions and register-computed store values. This bridge labels the selected
scalar memory opcodes as relaxed GPU/global operations, matching Scalar.Text.
It does not assert that Graph.Valid is sufficient for arbitrary dependent PTX.
-/
namespace Ptx.Scalar.MemoryWitness

open Kernels

/-- The selected memory opcodes use aligned global u32 words and generic proxy.
The caller must justify byte alignment before using the word-index view. -/
def label (thread position : Nat) (effect : MemoryEffect) : Ptx.Occurrence :=
  ⟨some thread, position,
    ⟨match effect.kind with | .load => .load .relaxed | .store => .store .relaxed,
      effect.address.toNat / 4, effect.value⟩⟩

/-- Register-only and skipped instructions emit no memory label. Position is the
original dispatch index, not a program counter that could repeat in a loop. -/
def traceEvents (thread : Nat) (trace : List Scalar.Occurrence) : List Ptx.Occurrence :=
  (trace.mapIdx fun position occurrence => occurrence.memory.map (label thread position)).filterMap id

def initialEvents (memory : List Word) : List Ptx.Occurrence :=
  memory.mapIdx fun address value => ⟨none, address, ⟨.init, address, value⟩⟩

/-- Two candidate loads are supplied at their actual dispatch positions. -/
def reads (left right : Word) (position : Nat) : Option Word :=
  if position = 0 then some left else if position = 1 then some right else none

def candidateRun (x y old left right : Word)
    (registers : Nat → Word) (addresses : Nat → Scalar.Address)
    (predicates : Nat → Bool) : RunResult :=
  runWith 5 (reads left right) addLane (laneStart x y old [] registers addresses predicates)

def events (x y old left right : Word) (registers : Nat → Word)
    (addresses : Nat → Scalar.Address) (predicates : Nat → Bool) : List Ptx.Occurrence :=
  initialEvents [x,y,old] ++
    traceEvents 0 (candidateRun x y old left right registers addresses predicates).trace

/-- The table is derived from load/load/add/register-store/exit execution. -/
theorem events_eq (x y old left right : Word) (registers addresses predicates) :
    events x y old left right registers addresses predicates =
      [⟨none,0,⟨.init,0,x⟩⟩, ⟨none,1,⟨.init,1,y⟩⟩, ⟨none,2,⟨.init,2,old⟩⟩,
       ⟨some 0,0,⟨.load .relaxed,0,left⟩⟩,
       ⟨some 0,1,⟨.load .relaxed,1,right⟩⟩,
       ⟨some 0,3,⟨.store .relaxed,2,left+right⟩⟩] := by
  simp [events, initialEvents, traceEvents, candidateRun, runWith, stepWith, eval,
    addLane, laneStart, Instr.plain, Guard.eval, Operand64.eval, Operand32.eval,
    BinOp.eval, update, addressIndex, reads, occurrence, label]

/-- Labels are generated by the scalar run; sources/coherence alone are candidates. -/
def graph (x y old left right : Word) (registers : Nat → Word)
    (addresses : Nat → Scalar.Address) (predicates : Nat → Bool)
    (source : Fin 6 → Fin 6) (co : Fin 6 → Fin 6 → Bool) : Graph 6 :=
  ⟨fun i => (events x y old left right registers addresses predicates).get
    ⟨i.val, by rw [events_eq]; exact i.isLt⟩, source, co⟩

theorem graph_event (x y old left right : Word) (registers addresses predicates)
    (source co) (i : Fin 6) :
    (graph x y old left right registers addresses predicates source co).event i =
      ([⟨none,0,⟨.init,0,x⟩⟩, ⟨none,1,⟨.init,1,y⟩⟩, ⟨none,2,⟨.init,2,old⟩⟩,
       ⟨some 0,0,⟨.load .relaxed,0,left⟩⟩,
       ⟨some 0,1,⟨.load .relaxed,1,right⟩⟩,
       ⟨some 0,3,⟨.store .relaxed,2,left+right⟩⟩] : List Ptx.Occurrence).get i := by
  simp [graph, events_eq]

@[simp] theorem graph_source (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).source = source := rfl

@[simp] theorem graph_event0 (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).event 0 =
      ⟨none,0,⟨.init,0,x⟩⟩ := by rw [graph_event]; rfl

@[simp] theorem graph_event1 (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).event 1 =
      ⟨none,1,⟨.init,1,y⟩⟩ := by rw [graph_event]; rfl

@[simp] theorem graph_event2 (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).event 2 =
      ⟨none,2,⟨.init,2,old⟩⟩ := by rw [graph_event]; rfl

@[simp] theorem graph_event3 (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).event 3 =
      ⟨some 0,0,⟨.load .relaxed,0,left⟩⟩ := by rw [graph_event]; rfl

@[simp] theorem graph_event4 (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).event 4 =
      ⟨some 0,1,⟨.load .relaxed,1,right⟩⟩ := by rw [graph_event]; rfl

@[simp] theorem graph_event5 (x y old left right : Word) (registers addresses predicates)
    (source co) : (graph x y old left right registers addresses predicates source co).event 5 =
      ⟨some 0,3,⟨.store .relaxed,2,left+right⟩⟩ := by rw [graph_event]; rfl

/-- Candidate load choices cannot affect the initial input words. -/
theorem candidate_result (x y old left right : Word) (registers addresses predicates) :
    (candidateRun x y old left right registers addresses predicates).status = .halted ∧
    (candidateRun x y old left right registers addresses predicates).state.memory =
      [x,y,left+right] := by
  simp [candidateRun, runWith, stepWith, eval, addLane, laneStart, Instr.plain,
    Guard.eval, Operand64.eval, Operand32.eval, BinOp.eval, update, addressIndex, reads]

/-- Both input addresses have only their initialization as a possible write.
This holds for every candidate source/coherence choice, without an NTA premise. -/
theorem input_sources (x y old left right : Word) (registers addresses predicates)
    (source co) (sources : (graph x y old left right registers addresses predicates source co).Sources) :
    left = x ∧ right = y := by
  have cases (i : Fin 6) : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ i = 5 := by omega
  constructor
  · have h := sources.compatible 3 (by simp [Graph.read])
    simp only [graph_source, graph_event3] at h
    rcases cases (source 3) with he | he | he | he | he | he
    all_goals rw [he] at h
    all_goals simp [Graph.write, Graph.sameAddress] at h
    exact h.symm
  · have h := sources.compatible 4 (by simp [Graph.read])
    simp only [graph_source, graph_event4] at h
    rcases cases (source 4) with he | he | he | he | he | he
    all_goals rw [he] at h
    all_goals simp [Graph.write, Graph.sameAddress] at h
    exact h.symm

/-- Universal input correspondence for this actual register-store kernel needs
only source compatibility; it is not inferred from a smaller admitted subset. -/
theorem candidate_correct (x y old left right : Word) (registers addresses predicates)
    (source co) (sources : (graph x y old left right registers addresses predicates source co).Sources) :
    (candidateRun x y old left right registers addresses predicates).status = .halted ∧
    (candidateRun x y old left right registers addresses predicates).state.memory = [x,y,x+y] := by
  obtain ⟨rfl,rfl⟩ := input_sources x y old left right registers addresses predicates source co sources
  exact candidate_result _ _ _ _ _ _ _ _

def witnessSource (i : Fin 6) : Fin 6 := if i = 4 then 1 else 0
def witnessCo (a b : Fin 6) : Bool := a == 2 && b == 5

def witness (x y old : Word) (registers : Nat → Word)
    (addresses : Nat → Scalar.Address) (predicates : Nat → Bool) : Graph 6 :=
  graph x y old x y registers addresses predicates witnessSource witnessCo


def upper (a b : Fin 6) : Prop := 3 ≤ a.val ∧ a.val < b.val

set_option synthInstance.maxSize 4096
local macro "finite_check" : tactic => `(tactic|
  (simp [Graph.baseEdge, Graph.sync, Graph.releasePattern, Graph.acquirePattern,
    Graph.observation, Graph.rf, Graph.morallyStrong, Graph.initial, Graph.release,
    Graph.acquire, Graph.po, Graph.sameAddress, Graph.read, Graph.write,
    Graph.coherence, Graph.upperCause, Graph.locationEdge, Graph.communication,
    witness, graph, events_eq, witnessSource, witnessCo, upper,
    Fin.forall_fin_succ, Fin.exists_fin_succ] <;> first | trivial | (constructor <;> trivial) | decide))

/-- The actual run has a compatible memory graph for arbitrary input words and
initial registers. Every read is constructively sourced from initialization. -/
theorem witness_valid (x y old : Word) (registers addresses predicates) :
    (witness x y old registers addresses predicates).Valid := by
  apply Graph.valid_of_certificate (upper := upper) (rank := Fin.val)
  exact {
    sources := ⟨by finite_check⟩
    co := ⟨by finite_check, by finite_check, by finite_check, by finite_check, by finite_check⟩
    edge_included := by finite_check
    upper_trans := by finite_check
    upper_irrefl := by finite_check
    coherence_cause := by finite_check
    no_future := by finite_check
    no_stale := by finite_check
    location_rank := by finite_check
  }

/-- For the sourced input values, the candidate run is exactly the concrete
sequential run, including all registers and every dynamic occurrence. -/
theorem candidate_eq_concrete (x y old : Word) (registers addresses predicates) :
    candidateRun x y old x y registers addresses predicates =
      run 5 addLane (laneStart x y old [] registers addresses predicates) := by
  simp [candidateRun, run, runWith, stepWith, eval, addLane, laneStart, Instr.plain,
    Guard.eval, Operand64.eval, Operand32.eval, BinOp.eval, update, addressIndex, reads]

/-- The word-index label preserves the original byte address when aligned. -/
theorem label_preserves_address (thread position : Nat) (effect : MemoryEffect)
    (aligned : effect.address.toNat % 4 = 0) :
    Ptx.byteAddress (label thread position effect).effect.address = effect.address.toNat := by
  have division := Nat.mod_add_div effect.address.toNat 4
  simpa [label, Ptx.byteAddress, aligned] using division

/-- The relational witness labels precisely the actual scalar run's memory effects. -/
theorem witness_events_from_run (x y old : Word) (registers addresses predicates) :
    events x y old x y registers addresses predicates =
      initialEvents [x,y,old] ++
        traceEvents 0 (run 5 addLane (laneStart x y old [] registers addresses predicates)).trace := by
  simp only [events, candidate_eq_concrete]

/-- A completed concrete run, its final memory, and its constructed memory-order
witness coexist for arbitrary input values and initial register assignments. -/
theorem constructive_execution (x y old : Word) (registers addresses predicates) :
    let start := laneStart x y old [] registers addresses predicates
    let result := run 5 addLane start
    Scalar.Runs addLane (fun _ => none) start result ∧
      result.status = .halted ∧ result.state.memory = [x,y,x+y] ∧
      (witness x y old registers addresses predicates).Valid := by
  obtain ⟨halted, memory, _⟩ := add_lane_result x y old [] registers addresses predicates
  exact ⟨run_sound _ _ _, halted, memory, witness_valid _ _ _ _ _ _⟩

end Ptx.Scalar.MemoryWitness
