import PtxReluAccuracy
import PtxAffineBackward
import PtxAffineSquareKernel
import PtxBinary32.Affine
import PtxBinary32.Mixed
import PtxBinary32.Instructions
import PtxTorchLean
import PtxTensorBridge
import PtxBinary32
import PtxBinary32Examples
import PtxBinary32Bounds
import PtxBinary32Error

/-! Explicit public integration endpoints and binary32 reference dependencies.
Fresh elaboration is checked by check.py; imported build logs are not reused. -/

#print axioms PtxTorchLean.affineSquare
#print axioms PtxTorchLean.forward_polynomial
#print axioms PtxTorchLean.checked_vjp
#print axioms PtxTorchLean.exact_tape_success_vjp
#print axioms PtxTorchLean.checked_success
#print axioms PtxTorchLean.checked_success_vjp
#print axioms PtxTorchLean.unsigned_min_scalar_embedding

#print axioms PtxTorchLean.TensorBridge.view_apply
#print axioms PtxTorchLean.TensorBridge.view_map
#print axioms PtxTorchLean.TensorBridge.layout_bounds
#print axioms PtxTorchLean.TensorBridge.realView_eq_map
#print axioms PtxTorchLean.TensorBridge.completed_unsigned
#print axioms PtxTorchLean.TensorBridge.completed_unsigned_tensor
#print axioms PtxTorchLean.TensorBridge.completed_real_add
#print axioms PtxTorchLean.TensorBridge.completed_bounds
#print axioms PtxTorchLean.TensorBridge.candidate_unsigned_tensor
#print axioms PtxTorchLean.TensorBridge.candidate_execution_agree
#print axioms PtxTorchLean.TensorBridge.execution_exists
#print axioms PtxTorchLean.TensorBridge.real_execution_exists
#print axioms PtxTorchLean.TensorBridge.view_bounded_apply
#print axioms PtxTorchLean.TensorBridge.wraparound_execution
#print axioms PtxTorchLean.TensorBridge.wraparound_not_fitting

#print axioms Ptx.Binary32.encode_decode
#print axioms Ptx.Binary32.decode_encode
#print axioms Ptx.Binary32.finiteReal_none
#print axioms Ptx.Binary32.finiteReal_some
#print axioms Ptx.Binary32.finiteReal_isSome
#print axioms Ptx.Binary32.finite_not_nan
#print axioms Ptx.Binary32.envelope_self
#print axioms Ptx.Binary32.envelope_exists
#print axioms Ptx.Binary32.envelope_nan
#print axioms Ptx.Binary32.envelope_non_nan
#print axioms Ptx.Binary32.envelope_finite_eq
#print axioms Ptx.Binary32.envelope_finite
#print axioms Ptx.Binary32.results_exists
#print axioms Ptx.Binary32.reference_round
#print axioms Ptx.Binary32.results_round
#print axioms Ptx.Binary32.results_abs_error
#print axioms Ptx.Binary32.decode
#print axioms Ptx.Binary32.encode
#print axioms Ptx.Binary32.isNaN
#print axioms Ptx.Binary32.isFinite
#print axioms Ptx.Binary32.finiteReal
#print axioms Ptx.Binary32.Envelope
#print axioms Ptx.Binary32.reference
#print axioms Ptx.Binary32.Results
#print axioms Ptx.Binary32.exact

#print axioms Ptx.Binary32.Examples.signed_zero_bits_distinct
#print axioms Ptx.Binary32.Examples.zero_signs_finite
#print axioms Ptx.Binary32.Examples.smallest_subnormal
#print axioms Ptx.Binary32.Examples.normal_boundary
#print axioms Ptx.Binary32.Examples.ordinary_add
#print axioms Ptx.Binary32.Examples.tie_even_down
#print axioms Ptx.Binary32.Examples.tie_odd_up
#print axioms Ptx.Binary32.Examples.subnormal_add_preserved
#print axioms Ptx.Binary32.Examples.negative_zero_product
#print axioms Ptx.Binary32.Examples.zero_sign_add
#print axioms Ptx.Binary32.Examples.finite_inputs_overflow
#print axioms Ptx.Binary32.Examples.infinity_opposite_invalid
#print axioms Ptx.Binary32.Examples.infinity_times_zero_invalid
#print axioms Ptx.Binary32.Examples.nan_payload_freedom
#print axioms Ptx.Binary32.Examples.signaling_nan_envelope
#print axioms Ptx.Binary32.Examples.exceptional_not_real

#print axioms Ptx.Binary32.Bounds.maxFinite_eq
#print axioms Ptx.Binary32.Bounds.finiteReal_spec
#print axioms Ptx.Binary32.Bounds.reference_finite
#print axioms Ptx.Binary32.Bounds.round_of_range
#print axioms Ptx.Binary32.Bounds.results_error
#print axioms Ptx.Binary32.Bounds.finite_result_exists
#print axioms Ptx.Binary32.Bounds.add_range_of_magnitudes
#print axioms Ptx.Binary32.Bounds.mul_range_of_magnitudes
#print axioms Ptx.Binary32.Bounds.unit_range
#print axioms Ptx.Binary32.Bounds.positive_one_real
#print axioms Ptx.Binary32.Bounds.negative_one_real
#print axioms Ptx.Binary32.Bounds.one_negative_one_results

#print axioms Ptx.Binary32.Error.budget_nonnegative
#print axioms Ptx.Binary32.Error.add_propagation
#print axioms Ptx.Binary32.Error.mul_propagation
#print axioms Ptx.Binary32.Error.add_results
#print axioms Ptx.Binary32.Error.mul_results
#print axioms Ptx.Binary32.Error.add_exists
#print axioms Ptx.Binary32.Error.mul_exists
#print axioms Ptx.Binary32.Error.rounded_add_range
#print axioms Ptx.Binary32.Error.affine_results
#print axioms Ptx.Binary32.Error.affine_exists

#print axioms Ptx.Scalar.Binary32.Instr
#print axioms Ptx.Scalar.Binary32.Occurrence
#print axioms Ptx.Scalar.Binary32.occurrence
#print axioms Ptx.Scalar.Binary32.SupportedTarget
#print axioms Ptx.Scalar.Binary32.Eval
#print axioms Ptx.Scalar.Binary32.Step
#print axioms Ptx.Scalar.Binary32.eval_true_iff
#print axioms Ptx.Scalar.Binary32.eval_false_iff
#print axioms Ptx.Scalar.Binary32.eval_destination
#print axioms Ptx.Scalar.Binary32.eval_frame
#print axioms Ptx.Scalar.Binary32.eval_other
#print axioms Ptx.Scalar.Binary32.eval_event
#print axioms Ptx.Scalar.Binary32.eval_exists
#print axioms Ptx.Scalar.Binary32.step_origin
#print axioms Ptx.Scalar.Binary32.step_exists
#print axioms Ptx.Scalar.Binary32.step_no_fetch
#print axioms Ptx.Scalar.Binary32.step_unsupported_target
#print axioms Ptx.Scalar.Binary32.Text.mnemonic
#print axioms Ptx.Scalar.Binary32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Binary32.Text.decode
#print axioms Ptx.Scalar.Binary32.Text.encode
#print axioms Ptx.Scalar.Binary32.Text.decode_encode
#print axioms Ptx.Scalar.Binary32.Text.decode_iff
#print axioms Ptx.Scalar.Binary32.signed_zero_bits
#print axioms Ptx.Scalar.Binary32.subnormal_bits
#print axioms Ptx.Scalar.Binary32.negative_guard_exec
#print axioms Ptx.Scalar.Binary32.negative_guard_skip
#print axioms Ptx.Scalar.Binary32.alias_add_bits

#print axioms Ptx.Scalar.Mixed.Instr
#print axioms Ptx.Scalar.Mixed.Event
#print axioms Ptx.Scalar.Mixed.Event.memory
#print axioms Ptx.Scalar.Mixed.Event.pc
#print axioms Ptx.Scalar.Mixed.Event.instruction
#print axioms Ptx.Scalar.Mixed.Outcome
#print axioms Ptx.Scalar.Mixed.liftScalar
#print axioms Ptx.Scalar.Mixed.Eval
#print axioms Ptx.Scalar.Mixed.Eligible
#print axioms Ptx.Scalar.Mixed.Dispatch
#print axioms Ptx.Scalar.Mixed.eligible_binary32
#print axioms Ptx.Scalar.Mixed.eval_scalar_iff
#print axioms Ptx.Scalar.Mixed.eval_binary32_iff
#print axioms Ptx.Scalar.Mixed.dispatch_fetch
#print axioms Ptx.Scalar.Mixed.dispatch_missing
#print axioms Ptx.Scalar.Mixed.dispatch_exists
#print axioms Ptx.Scalar.Mixed.Path
#print axioms Ptx.Scalar.Mixed.Advances
#print axioms Ptx.Scalar.Mixed.Path.append
#print axioms Ptx.Scalar.Mixed.Path.invariant
#print axioms Ptx.Scalar.Mixed.Path.event_origin
#print axioms Ptx.Scalar.Mixed.Run
#print axioms Ptx.Scalar.Mixed.Run.not_exhausted
#print axioms Ptx.Scalar.Mixed.scalar_next_iff
#print axioms Ptx.Scalar.Mixed.scalar_halted_iff
#print axioms Ptx.Scalar.Mixed.eval_event_origin
#print axioms Ptx.Scalar.Mixed.dispatch_event_origin
#print axioms Ptx.Scalar.Mixed.eval_next_safe
#print axioms Ptx.Scalar.Mixed.eval_halted
#print axioms Ptx.Scalar.Mixed.dispatch_next_safe
#print axioms Ptx.Scalar.Mixed.dispatch_halted
#print axioms Ptx.Scalar.Mixed.Path.memory_length
#print axioms Ptx.Scalar.Mixed.Path.memory_safe
#print axioms Ptx.Scalar.Mixed.Run.memory_length
#print axioms Ptx.Scalar.Mixed.Run.memory_safe
#print axioms Ptx.Scalar.Mixed.StoresTo
#print axioms Ptx.Scalar.Mixed.eval_frame
#print axioms Ptx.Scalar.Mixed.dispatch_frame
#print axioms Ptx.Scalar.Mixed.Path.frame
#print axioms Ptx.Scalar.Mixed.Run.frame
#print axioms Ptx.Scalar.Mixed.Run.unfold
#print axioms Ptx.Scalar.Mixed.Run.scalar_next_iff
#print axioms Ptx.Scalar.Mixed.Run.scalar_halted_iff
#print axioms Ptx.Scalar.Mixed.Run.binary32_iff

#print axioms Ptx.Scalar.Affine.load
#print axioms Ptx.Scalar.Affine.multiply
#print axioms Ptx.Scalar.Affine.addition
#print axioms Ptx.Scalar.Affine.store
#print axioms Ptx.Scalar.Affine.exit
#print axioms Ptx.Scalar.Affine.program
#print axioms Ptx.Scalar.Affine.Initial
#print axioms Ptx.Scalar.Affine.input
#print axioms Ptx.Scalar.Affine.outputIndex
#print axioms Ptx.Scalar.Affine.afterLeft
#print axioms Ptx.Scalar.Affine.afterRight
#print axioms Ptx.Scalar.Affine.afterBias
#print axioms Ptx.Scalar.Affine.afterMultiply
#print axioms Ptx.Scalar.Affine.afterAdd
#print axioms Ptx.Scalar.Affine.finish
#print axioms Ptx.Scalar.Affine.loadEvent
#print axioms Ptx.Scalar.Affine.trace
#print axioms Ptx.Scalar.Affine.run_iff
#print axioms Ptx.Scalar.Affine.run_exists
#print axioms Ptx.Scalar.Affine.trace_length
#print axioms Ptx.Scalar.Affine.trace_positions
#print axioms Ptx.Scalar.Affine.trace_instructions
#print axioms Ptx.Scalar.Affine.trace_memory
#print axioms Ptx.Scalar.Affine.finish_frame
#print axioms Ptx.Scalar.Affine.finish_registers
#print axioms Ptx.Scalar.Affine.finish_other_register
#print axioms Ptx.Scalar.Affine.finish_output
#print axioms Ptx.Scalar.Affine.finish_other_memory
#print axioms Ptx.Scalar.Affine.run_completed
#print axioms Ptx.Scalar.Affine.stored_error
#print axioms Ptx.Scalar.Affine.advance_pc
#print axioms Ptx.Scalar.Affine.path_control
#print axioms Ptx.Scalar.Affine.path_bound
#print axioms Ptx.Scalar.Affine.memoryProjection
#print axioms Ptx.Scalar.Affine.memoryWitness
#print axioms Ptx.Scalar.Affine.memoryWitness_valid
#print axioms Ptx.Scalar.Affine.trace_memory_witness
#print axioms Ptx.Scalar.Affine.run_memory_witness
#print axioms Ptx.Scalar.Affine.eventAt
#print axioms Ptx.Scalar.Affine.RegisterDependency
#print axioms Ptx.Scalar.Affine.register_dependency_forward
#print axioms Ptx.Scalar.Affine.register_dependency_acyclic
#print axioms Ptx.Scalar.Affine.run_grounded
#print axioms Ptx.Scalar.Affine.disjointFixture
#print axioms Ptx.Scalar.Affine.disjoint_example
#print axioms Ptx.Scalar.Affine.aliasFixture
#print axioms Ptx.Scalar.Affine.all_alias_example

-- Serialized storage, actual two-kernel forward and generated exact backward.
#print axioms Ptx.Scalar.Sequential.Argument
#print axioms Ptx.Scalar.Sequential.Seed
#print axioms Ptx.Scalar.Sequential.start
#print axioms Ptx.Scalar.Sequential.start_pc
#print axioms Ptx.Scalar.Sequential.start_regs
#print axioms Ptx.Scalar.Sequential.start_preds
#print axioms Ptx.Scalar.Sequential.start_memory
#print axioms Ptx.Scalar.Sequential.start_argument
#print axioms Ptx.Scalar.Sequential.start_other
#print axioms Ptx.Scalar.Sequential.Request
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.cell
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.present
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.owner
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.identities
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.run
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.writeback
#print axioms Ptx.Scalar.Sequential.launch_exists
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.exact_writeback
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.run_from
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.writeback_lookup
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.environment_unchanged
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.other_cell
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.environment_safe
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.final_environment_safe
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.word_frame
#print axioms Ptx.Scalar.Sequential.SuccessfulLaunch.storage_step
#print axioms Ptx.Scalar.Sequential.no_launch_absent
#print axioms Ptx.Scalar.Sequential.no_launch_wrong_owner
#print axioms Ptx.Scalar.Sequential.no_launch_wrong_identity
#print axioms Ptx.Scalar.Sequential.no_launch_after_release
#print axioms Ptx.Scalar.Sequential.Chain
#print axioms Ptx.Scalar.Sequential.Chain.append
#print axioms Ptx.Scalar.Sequential.Chain.cons_iff
#print axioms Ptx.Scalar.Sequential.Chain.nil_iff
#print axioms Ptx.Scalar.Sequential.Chain.two_iff
#print axioms Ptx.Scalar.Sequential.Chain.storage_history
#print axioms Ptx.Scalar.Sequential.Chain.invariant
#print axioms Ptx.Scalar.Sequential.Chain.old_absent
#print axioms PtxTorchLean.AffineSquareVJP.scalarShape
#print axioms PtxTorchLean.AffineSquareVJP.inputs
#print axioms PtxTorchLean.AffineSquareVJP.graph
#print axioms PtxTorchLean.AffineSquareVJP.sensitivities
#print axioms PtxTorchLean.AffineSquareVJP.forward_value
#print axioms PtxTorchLean.AffineSquareVJP.generated_vjp
#print axioms PtxTorchLean.AffineSquareVJP.forward_tensor
#print axioms PtxTorchLean.AffineSquareVJP.checked_result
#print axioms PtxTorchLean.AffineSquareVJP.sensitivities_adjoint
#print axioms PtxTorchLean.AffineSquareVJP.checked_example
#print axioms Ptx.Binary32.SquareError.roundedAffine
#print axioms Ptx.Binary32.SquareError.Results
#print axioms Ptx.Binary32.SquareError.budget
#print axioms Ptx.Binary32.SquareError.zero_real
#print axioms Ptx.Binary32.SquareError.affine_value
#print axioms Ptx.Binary32.SquareError.budget_expansion
#print axioms Ptx.Binary32.SquareError.results_error
#print axioms Ptx.Binary32.SquareError.results_exists
#print axioms PtxTorchLean.AffineSquareKernel.memory
#print axioms PtxTorchLean.AffineSquareKernel.outputMemory
#print axioms PtxTorchLean.AffineSquareKernel.firstArgs
#print axioms PtxTorchLean.AffineSquareKernel.secondArgs
#print axioms PtxTorchLean.AffineSquareKernel.firstStart
#print axioms PtxTorchLean.AffineSquareKernel.secondStart
#print axioms PtxTorchLean.AffineSquareKernel.request
#print axioms PtxTorchLean.AffineSquareKernel.firstRequest
#print axioms PtxTorchLean.AffineSquareKernel.secondRequest
#print axioms PtxTorchLean.AffineSquareKernel.first_initial
#print axioms PtxTorchLean.AffineSquareKernel.second_initial
#print axioms PtxTorchLean.AffineSquareKernel.first_run_iff
#print axioms PtxTorchLean.AffineSquareKernel.second_run_iff
#print axioms PtxTorchLean.AffineSquareKernel.first_memory
#print axioms PtxTorchLean.AffineSquareKernel.second_memory
#print axioms PtxTorchLean.AffineSquareKernel.launches_correct
#print axioms PtxTorchLean.AffineSquareKernel.pipeline_of_results
#print axioms PtxTorchLean.AffineSquareKernel.pipeline_exists
#print axioms PtxTorchLean.AffineSquareKernel.pipeline_correct
#print axioms PtxTorchLean.AffineSquareKernel.pipeline_frame
#print axioms PtxTorchLean.AffineSquareKernel.stored_forward_error
#print axioms PtxTorchLean.AffineSquareKernel.two_launch_example
#print axioms PtxTorchLean.AffineSquareKernel.second_launch_after_release_rejected

-- Independently authored recomputing backward: executions, values and generated VJP.
#print axioms Ptx.Binary32.BackwardError.roundedProduct
#print axioms Ptx.Binary32.BackwardError.roundedBase
#print axioms Ptx.Binary32.BackwardError.StageRange
#print axioms Ptx.Binary32.BackwardError.Guards
#print axioms Ptx.Binary32.BackwardError.stageBudget
#print axioms Ptx.Binary32.BackwardError.qBudget
#print axioms Ptx.Binary32.BackwardError.baseBudget
#print axioms Ptx.Binary32.BackwardError.parameterBudget
#print axioms Ptx.Binary32.BackwardError.Results
#print axioms Ptx.Binary32.BackwardError.two_real
#print axioms Ptx.Binary32.BackwardError.stage_error
#print axioms Ptx.Binary32.BackwardError.results_error
#print axioms Ptx.Binary32.BackwardError.results_exists
#print axioms Ptx.GradientView.Triple
#print axioms Ptx.GradientView.Words
#print axioms Ptx.GradientView.decode
#print axioms Ptx.GradientView.component
#print axioms Ptx.GradientView.Componentwise
#print axioms Ptx.GradientView.Approximates
#print axioms Ptx.GradientView.component_inputs
#print axioms Ptx.GradientView.componentwise_iff
#print axioms Ptx.GradientView.componentwise_inputs_iff
#print axioms Ptx.GradientView.decode_of_finite
#print axioms Ptx.GradientView.decode_some_iff
#print axioms Ptx.GradientView.decode_none_iff
#print axioms Ptx.GradientView.nonfinite_rejected
#print axioms Ptx.GradientView.not_approximates_of_nonfinite
#print axioms Ptx.GradientView.approximates_iff
#print axioms Ptx.GradientView.generated_iff
#print axioms Ptx.GradientView.generated_of_bounds_checked
#print axioms Ptx.GradientView.signed_zero_same_view
#print axioms Ptx.Scalar.BackwardPipeline.Data
#print axioms Ptx.Scalar.BackwardPipeline.Data.words
#print axioms Ptx.Scalar.BackwardPipeline.Data.left
#print axioms Ptx.Scalar.BackwardPipeline.Data.right
#print axioms Ptx.Scalar.BackwardPipeline.Data.update
#print axioms Ptx.Scalar.BackwardPipeline.outputData
#print axioms Ptx.Scalar.BackwardPipeline.arguments
#print axioms Ptx.Scalar.BackwardPipeline.stageStart
#print axioms Ptx.Scalar.BackwardPipeline.request
#print axioms Ptx.Scalar.BackwardPipeline.requests
#print axioms Ptx.Scalar.BackwardPipeline.Results
#print axioms Ptx.Scalar.BackwardPipeline.stage_initial
#print axioms Ptx.Scalar.BackwardPipeline.stage_run_iff
#print axioms Ptx.Scalar.BackwardPipeline.finish_words
#print axioms Ptx.Scalar.BackwardPipeline.stage_launch_correct
#print axioms Ptx.Scalar.BackwardPipeline.stage_of_results
#print axioms Ptx.Scalar.BackwardPipeline.stage_trace_safe
#print axioms Ptx.Scalar.BackwardPipeline.results_exists
#print axioms Ptx.Scalar.BackwardPipeline.four_launches_iff
#print axioms Ptx.Scalar.BackwardPipeline.launches_correct
#print axioms Ptx.Scalar.BackwardPipeline.pipeline_correct
#print axioms Ptx.Scalar.BackwardPipeline.pipeline_of_results
#print axioms Ptx.Scalar.BackwardPipeline.pipeline_exists
#print axioms Ptx.Scalar.BackwardPipeline.pipeline_other_allocation
#print axioms Ptx.Scalar.BackwardPipeline.words_tail
#print axioms Ptx.Scalar.BackwardPipeline.pipeline_memory_frame
#print axioms Ptx.Scalar.BackwardPipeline.stage_after_release_rejected
#print axioms PtxTorchLean.AffineBackward.Data
#print axioms PtxTorchLean.AffineBackward.recomputeArgs
#print axioms PtxTorchLean.AffineBackward.withSaved
#print axioms PtxTorchLean.AffineBackward.recomputeStart
#print axioms PtxTorchLean.AffineBackward.recomputeRequest
#print axioms PtxTorchLean.AffineBackward.requests
#print axioms PtxTorchLean.AffineBackward.recompute_initial
#print axioms PtxTorchLean.AffineBackward.recompute_run_iff
#print axioms PtxTorchLean.AffineBackward.recompute_memory
#print axioms PtxTorchLean.AffineBackward.recompute_correct
#print axioms PtxTorchLean.AffineBackward.recompute_exists
#print axioms PtxTorchLean.AffineBackward.budgetX
#print axioms PtxTorchLean.AffineBackward.budgetW
#print axioms PtxTorchLean.AffineBackward.budgetB
#print axioms PtxTorchLean.AffineBackward.results_approximate
#print axioms PtxTorchLean.AffineBackward.pipeline_correct
#print axioms PtxTorchLean.AffineBackward.pipeline_exists
#print axioms PtxTorchLean.AffineBackward.pipeline_other_allocation
#print axioms PtxTorchLean.AffineBackward.stored_backward_approximation
#print axioms PtxTorchLean.AffineBackward.fixture
#print axioms PtxTorchLean.AffineBackward.five_launch_example

-- ReLU neuron: actual generated backward, finite gate, execution and accuracy.
#print axioms PtxTorchLean.ReluVJP.scalarShape
#print axioms Ptx.Binary32.Relu.positive
#print axioms Ptx.Binary32.Relu.gate
#print axioms Ptx.Binary32.Relu.forward
#print axioms Ptx.Binary32.Relu.positive_iff
#print axioms Ptx.Binary32.Relu.zero_real
#print axioms Ptx.Binary32.Relu.gate_real
#print axioms Ptx.Binary32.Relu.forward_real
#print axioms Ptx.Binary32.Relu.forward_error
#print axioms Ptx.Binary32.Relu.sign_stable
#print axioms Ptx.Scalar.ReluGate.load
#print axioms Ptx.Scalar.ReluGate.zeroTest
#print axioms Ptx.Scalar.ReluGate.signTest
#print axioms Ptx.Scalar.ReluGate.clear
#print axioms Ptx.Scalar.ReluGate.store
#print axioms Ptx.Scalar.ReluGate.exit
#print axioms Ptx.Scalar.ReluGate.program
#print axioms Ptx.Scalar.ReluGate.Initial
#print axioms Ptx.Scalar.ReluGate.input
#print axioms Ptx.Scalar.ReluGate.afterLeft
#print axioms Ptx.Scalar.ReluGate.afterRight
#print axioms Ptx.Scalar.ReluGate.afterZeroTest
#print axioms Ptx.Scalar.ReluGate.afterZero
#print axioms Ptx.Scalar.ReluGate.afterSignTest
#print axioms Ptx.Scalar.ReluGate.afterClear
#print axioms Ptx.Scalar.ReluGate.finish
#print axioms Ptx.Scalar.ReluGate.run_iff
#print axioms Ptx.Scalar.ReluGate.run_exists
#print axioms Ptx.Scalar.ReluGate.run_memory
#print axioms PtxTorchLean.ReluVJP.inputs
#print axioms PtxTorchLean.ReluVJP.rawGraph
#print axioms PtxTorchLean.ReluVJP.graph
#print axioms PtxTorchLean.ReluVJP.gate
#print axioms PtxTorchLean.ReluVJP.sensitivities
#print axioms PtxTorchLean.ReluVJP.generated_vjp
#print axioms PtxTorchLean.ReluVJP.forward_value
#print axioms PtxTorchLean.ReluVJP.checked_result
#print axioms PtxTorchLean.ReluVJP.graph_correct_at
#print axioms PtxTorchLean.ReluVJP.sensitivities_adjoint
#print axioms PtxTorchLean.ReluKernel.Data
#print axioms PtxTorchLean.ReluKernel.Data.words
#print axioms PtxTorchLean.ReluKernel.Stage
#print axioms PtxTorchLean.ReluKernel.Stage.isGate
#print axioms PtxTorchLean.ReluKernel.program
#print axioms PtxTorchLean.ReluKernel.arguments
#print axioms PtxTorchLean.ReluKernel.Data.update
#print axioms PtxTorchLean.ReluKernel.Results
#print axioms PtxTorchLean.ReluKernel.stageStart
#print axioms PtxTorchLean.ReluKernel.request
#print axioms PtxTorchLean.ReluKernel.forwardStages
#print axioms PtxTorchLean.ReluKernel.backwardStages
#print axioms PtxTorchLean.ReluKernel.Evaluation
#print axioms PtxTorchLean.ReluKernel.run_correct
#print axioms PtxTorchLean.ReluKernel.run_exists
#print axioms PtxTorchLean.ReluKernel.launch_correct
#print axioms PtxTorchLean.ReluKernel.launch_exists
#print axioms PtxTorchLean.ReluKernel.pipeline_correct
#print axioms PtxTorchLean.ReluKernel.pipeline_exists
#print axioms PtxTorchLean.ReluKernel.launch_memory_safe
#print axioms PtxTorchLean.ReluKernel.pipeline_frame
#print axioms PtxTorchLean.ReluKernel.Evaluation.inputs_frame
#print axioms PtxTorchLean.ReluKernel.forward_values
#print axioms PtxTorchLean.ReluKernel.backward_values
#print axioms PtxTorchLean.ReluKernel.Inputs
#print axioms PtxTorchLean.ReluKernel.Inputs.budget
#print axioms PtxTorchLean.ReluKernel.Inputs.affine
#print axioms PtxTorchLean.ReluKernel.forward_accuracy
#print axioms PtxTorchLean.ReluKernel.BackwardInputs
#print axioms PtxTorchLean.ReluKernel.BackwardInputs.actualGate
#print axioms PtxTorchLean.ReluKernel.BackwardInputs.idealGate
#print axioms PtxTorchLean.ReluKernel.BackwardInputs.dxBudget
#print axioms PtxTorchLean.ReluKernel.BackwardInputs.dwBudget
#print axioms PtxTorchLean.ReluKernel.BackwardInputs.away
#print axioms PtxTorchLean.ReluKernel.backward_accuracy
#print axioms PtxTorchLean.ReluKernel.stored_forward_accuracy
#print axioms PtxTorchLean.ReluKernel.stored_backward_accuracy
