import PtxBinary32.Affine
import PtxBinary32.Mixed
import PtxBinary32.Instructions
import PtxTorchLean
import PtxTensorBridge
import PtxBinary32
import PtxBinary32Examples
import PtxBinary32Bounds
import PtxBinary32Error

/-! Explicit public integration endpoints and binary32 reference dependencies.
Fresh elaboration is checked by check.py; imported build logs are not reused. -/

#print axioms PtxTorchLean.affineSquare
#print axioms PtxTorchLean.forward_polynomial
#print axioms PtxTorchLean.checked_vjp
#print axioms PtxTorchLean.exact_tape_success_vjp
#print axioms PtxTorchLean.checked_success
#print axioms PtxTorchLean.checked_success_vjp
#print axioms PtxTorchLean.unsigned_min_scalar_embedding

#print axioms PtxTorchLean.TensorBridge.view_apply
#print axioms PtxTorchLean.TensorBridge.view_map
#print axioms PtxTorchLean.TensorBridge.layout_bounds
#print axioms PtxTorchLean.TensorBridge.realView_eq_map
#print axioms PtxTorchLean.TensorBridge.completed_unsigned
#print axioms PtxTorchLean.TensorBridge.completed_unsigned_tensor
#print axioms PtxTorchLean.TensorBridge.completed_real_add
#print axioms PtxTorchLean.TensorBridge.completed_bounds
#print axioms PtxTorchLean.TensorBridge.candidate_unsigned_tensor
#print axioms PtxTorchLean.TensorBridge.candidate_execution_agree
#print axioms PtxTorchLean.TensorBridge.execution_exists
#print axioms PtxTorchLean.TensorBridge.real_execution_exists
#print axioms PtxTorchLean.TensorBridge.view_bounded_apply
#print axioms PtxTorchLean.TensorBridge.wraparound_execution
#print axioms PtxTorchLean.TensorBridge.wraparound_not_fitting

#print axioms Ptx.Binary32.encode_decode
#print axioms Ptx.Binary32.decode_encode
#print axioms Ptx.Binary32.finiteReal_none
#print axioms Ptx.Binary32.finiteReal_some
#print axioms Ptx.Binary32.finiteReal_isSome
#print axioms Ptx.Binary32.finite_not_nan
#print axioms Ptx.Binary32.envelope_self
#print axioms Ptx.Binary32.envelope_exists
#print axioms Ptx.Binary32.envelope_nan
#print axioms Ptx.Binary32.envelope_non_nan
#print axioms Ptx.Binary32.envelope_finite_eq
#print axioms Ptx.Binary32.envelope_finite
#print axioms Ptx.Binary32.results_exists
#print axioms Ptx.Binary32.reference_round
#print axioms Ptx.Binary32.results_round
#print axioms Ptx.Binary32.results_abs_error
#print axioms Ptx.Binary32.decode
#print axioms Ptx.Binary32.encode
#print axioms Ptx.Binary32.isNaN
#print axioms Ptx.Binary32.isFinite
#print axioms Ptx.Binary32.finiteReal
#print axioms Ptx.Binary32.Envelope
#print axioms Ptx.Binary32.reference
#print axioms Ptx.Binary32.Results
#print axioms Ptx.Binary32.exact

#print axioms Ptx.Binary32.Examples.signed_zero_bits_distinct
#print axioms Ptx.Binary32.Examples.zero_signs_finite
#print axioms Ptx.Binary32.Examples.smallest_subnormal
#print axioms Ptx.Binary32.Examples.normal_boundary
#print axioms Ptx.Binary32.Examples.ordinary_add
#print axioms Ptx.Binary32.Examples.tie_even_down
#print axioms Ptx.Binary32.Examples.tie_odd_up
#print axioms Ptx.Binary32.Examples.subnormal_add_preserved
#print axioms Ptx.Binary32.Examples.negative_zero_product
#print axioms Ptx.Binary32.Examples.zero_sign_add
#print axioms Ptx.Binary32.Examples.finite_inputs_overflow
#print axioms Ptx.Binary32.Examples.infinity_opposite_invalid
#print axioms Ptx.Binary32.Examples.infinity_times_zero_invalid
#print axioms Ptx.Binary32.Examples.nan_payload_freedom
#print axioms Ptx.Binary32.Examples.signaling_nan_envelope
#print axioms Ptx.Binary32.Examples.exceptional_not_real

#print axioms Ptx.Binary32.Bounds.maxFinite_eq
#print axioms Ptx.Binary32.Bounds.finiteReal_spec
#print axioms Ptx.Binary32.Bounds.reference_finite
#print axioms Ptx.Binary32.Bounds.round_of_range
#print axioms Ptx.Binary32.Bounds.results_error
#print axioms Ptx.Binary32.Bounds.finite_result_exists
#print axioms Ptx.Binary32.Bounds.add_range_of_magnitudes
#print axioms Ptx.Binary32.Bounds.mul_range_of_magnitudes
#print axioms Ptx.Binary32.Bounds.unit_range
#print axioms Ptx.Binary32.Bounds.positive_one_real
#print axioms Ptx.Binary32.Bounds.negative_one_real
#print axioms Ptx.Binary32.Bounds.one_negative_one_results

#print axioms Ptx.Binary32.Error.budget_nonnegative
#print axioms Ptx.Binary32.Error.add_propagation
#print axioms Ptx.Binary32.Error.mul_propagation
#print axioms Ptx.Binary32.Error.add_results
#print axioms Ptx.Binary32.Error.mul_results
#print axioms Ptx.Binary32.Error.add_exists
#print axioms Ptx.Binary32.Error.mul_exists
#print axioms Ptx.Binary32.Error.rounded_add_range
#print axioms Ptx.Binary32.Error.affine_results
#print axioms Ptx.Binary32.Error.affine_exists

#print axioms Ptx.Scalar.Binary32.Instr
#print axioms Ptx.Scalar.Binary32.Occurrence
#print axioms Ptx.Scalar.Binary32.occurrence
#print axioms Ptx.Scalar.Binary32.SupportedTarget
#print axioms Ptx.Scalar.Binary32.Eval
#print axioms Ptx.Scalar.Binary32.Step
#print axioms Ptx.Scalar.Binary32.eval_true_iff
#print axioms Ptx.Scalar.Binary32.eval_false_iff
#print axioms Ptx.Scalar.Binary32.eval_destination
#print axioms Ptx.Scalar.Binary32.eval_frame
#print axioms Ptx.Scalar.Binary32.eval_other
#print axioms Ptx.Scalar.Binary32.eval_event
#print axioms Ptx.Scalar.Binary32.eval_exists
#print axioms Ptx.Scalar.Binary32.step_origin
#print axioms Ptx.Scalar.Binary32.step_exists
#print axioms Ptx.Scalar.Binary32.step_no_fetch
#print axioms Ptx.Scalar.Binary32.step_unsupported_target
#print axioms Ptx.Scalar.Binary32.Text.mnemonic
#print axioms Ptx.Scalar.Binary32.Text.supportedMnemonic
#print axioms Ptx.Scalar.Binary32.Text.decode
#print axioms Ptx.Scalar.Binary32.Text.encode
#print axioms Ptx.Scalar.Binary32.Text.decode_encode
#print axioms Ptx.Scalar.Binary32.Text.decode_iff
#print axioms Ptx.Scalar.Binary32.signed_zero_bits
#print axioms Ptx.Scalar.Binary32.subnormal_bits
#print axioms Ptx.Scalar.Binary32.negative_guard_exec
#print axioms Ptx.Scalar.Binary32.negative_guard_skip
#print axioms Ptx.Scalar.Binary32.alias_add_bits

#print axioms Ptx.Scalar.Mixed.Instr
#print axioms Ptx.Scalar.Mixed.Event
#print axioms Ptx.Scalar.Mixed.Event.memory
#print axioms Ptx.Scalar.Mixed.Event.pc
#print axioms Ptx.Scalar.Mixed.Event.instruction
#print axioms Ptx.Scalar.Mixed.Outcome
#print axioms Ptx.Scalar.Mixed.liftScalar
#print axioms Ptx.Scalar.Mixed.Eval
#print axioms Ptx.Scalar.Mixed.Eligible
#print axioms Ptx.Scalar.Mixed.Dispatch
#print axioms Ptx.Scalar.Mixed.eligible_binary32
#print axioms Ptx.Scalar.Mixed.eval_scalar_iff
#print axioms Ptx.Scalar.Mixed.eval_binary32_iff
#print axioms Ptx.Scalar.Mixed.dispatch_fetch
#print axioms Ptx.Scalar.Mixed.dispatch_missing
#print axioms Ptx.Scalar.Mixed.dispatch_exists
#print axioms Ptx.Scalar.Mixed.Path
#print axioms Ptx.Scalar.Mixed.Advances
#print axioms Ptx.Scalar.Mixed.Path.append
#print axioms Ptx.Scalar.Mixed.Path.invariant
#print axioms Ptx.Scalar.Mixed.Path.event_origin
#print axioms Ptx.Scalar.Mixed.Run
#print axioms Ptx.Scalar.Mixed.Run.not_exhausted
#print axioms Ptx.Scalar.Mixed.scalar_next_iff
#print axioms Ptx.Scalar.Mixed.scalar_halted_iff
#print axioms Ptx.Scalar.Mixed.eval_event_origin
#print axioms Ptx.Scalar.Mixed.dispatch_event_origin
#print axioms Ptx.Scalar.Mixed.eval_next_safe
#print axioms Ptx.Scalar.Mixed.eval_halted
#print axioms Ptx.Scalar.Mixed.dispatch_next_safe
#print axioms Ptx.Scalar.Mixed.dispatch_halted
#print axioms Ptx.Scalar.Mixed.Path.memory_length
#print axioms Ptx.Scalar.Mixed.Path.memory_safe
#print axioms Ptx.Scalar.Mixed.Run.memory_length
#print axioms Ptx.Scalar.Mixed.Run.memory_safe
#print axioms Ptx.Scalar.Mixed.StoresTo
#print axioms Ptx.Scalar.Mixed.eval_frame
#print axioms Ptx.Scalar.Mixed.dispatch_frame
#print axioms Ptx.Scalar.Mixed.Path.frame
#print axioms Ptx.Scalar.Mixed.Run.frame
#print axioms Ptx.Scalar.Mixed.Run.unfold
#print axioms Ptx.Scalar.Mixed.Run.scalar_next_iff
#print axioms Ptx.Scalar.Mixed.Run.scalar_halted_iff
#print axioms Ptx.Scalar.Mixed.Run.binary32_iff

#print axioms Ptx.Scalar.Affine.load
#print axioms Ptx.Scalar.Affine.multiply
#print axioms Ptx.Scalar.Affine.addition
#print axioms Ptx.Scalar.Affine.store
#print axioms Ptx.Scalar.Affine.exit
#print axioms Ptx.Scalar.Affine.program
#print axioms Ptx.Scalar.Affine.Initial
#print axioms Ptx.Scalar.Affine.input
#print axioms Ptx.Scalar.Affine.outputIndex
#print axioms Ptx.Scalar.Affine.afterLeft
#print axioms Ptx.Scalar.Affine.afterRight
#print axioms Ptx.Scalar.Affine.afterBias
#print axioms Ptx.Scalar.Affine.afterMultiply
#print axioms Ptx.Scalar.Affine.afterAdd
#print axioms Ptx.Scalar.Affine.finish
#print axioms Ptx.Scalar.Affine.loadEvent
#print axioms Ptx.Scalar.Affine.trace
#print axioms Ptx.Scalar.Affine.run_iff
#print axioms Ptx.Scalar.Affine.run_exists
#print axioms Ptx.Scalar.Affine.trace_length
#print axioms Ptx.Scalar.Affine.trace_positions
#print axioms Ptx.Scalar.Affine.trace_instructions
#print axioms Ptx.Scalar.Affine.trace_memory
#print axioms Ptx.Scalar.Affine.finish_frame
#print axioms Ptx.Scalar.Affine.finish_registers
#print axioms Ptx.Scalar.Affine.finish_other_register
#print axioms Ptx.Scalar.Affine.finish_output
#print axioms Ptx.Scalar.Affine.finish_other_memory
#print axioms Ptx.Scalar.Affine.run_completed
#print axioms Ptx.Scalar.Affine.stored_error
#print axioms Ptx.Scalar.Affine.advance_pc
#print axioms Ptx.Scalar.Affine.path_control
#print axioms Ptx.Scalar.Affine.path_bound
#print axioms Ptx.Scalar.Affine.memoryProjection
#print axioms Ptx.Scalar.Affine.memoryWitness
#print axioms Ptx.Scalar.Affine.memoryWitness_valid
#print axioms Ptx.Scalar.Affine.trace_memory_witness
#print axioms Ptx.Scalar.Affine.run_memory_witness
#print axioms Ptx.Scalar.Affine.eventAt
#print axioms Ptx.Scalar.Affine.RegisterDependency
#print axioms Ptx.Scalar.Affine.register_dependency_forward
#print axioms Ptx.Scalar.Affine.register_dependency_acyclic
#print axioms Ptx.Scalar.Affine.run_grounded
#print axioms Ptx.Scalar.Affine.disjointFixture
#print axioms Ptx.Scalar.Affine.disjoint_example
#print axioms Ptx.Scalar.Affine.aliasFixture
#print axioms Ptx.Scalar.Affine.all_alias_example
