import Ptx
import NN.Proofs.Autograd.Runtime.Link.GraphComposition
import NN.Proofs.Autograd.Tape.Nodes.Arithmetic
import NN.Proofs.Autograd.Runtime.Link.BackwardDenseGraph

/-!
A genuine upstream graph: `(x * weight + bias)^2`, applied independently at each
coordinate of an arbitrary tensor shape. Weight and bias are variable inputs.
The exact tape's reverse sweep is generated by TorchLean, not supplied here.
-/
namespace PtxTorchLean
open Spec TorchLean Proofs Proofs.Autograd
noncomputable section

/-- Input order is input, weight, bias; saved results are product, affine, square. -/
def affineSquare (s : Shape) : DGraph [s, s, s] [s, s, s] :=
  let x : Idx ([s, s, s] ++ []) s := ⟨⟨0, by simp⟩, rfl⟩
  let w : Idx ([s, s, s] ++ []) s := ⟨⟨1, by simp⟩, rfl⟩
  let product := DGraph.nil.snoc (TapeNodes.mul x w) (TapeNodes.mulFderiv x w)
  let p : Idx ([s, s, s] ++ [s]) s := ⟨⟨3, by simp⟩, rfl⟩
  let b : Idx ([s, s, s] ++ [s]) s := ⟨⟨2, by simp⟩, rfl⟩
  let affine := product.snoc (TapeNodes.add p b) (TapeNodes.addFderiv p b)
  let a : Idx ([s, s, s] ++ [s, s]) s := ⟨⟨4, by simp⟩, rfl⟩
  affine.snoc (TapeNodes.square a) (TapeNodes.squareFderiv a)

def output (s : Shape) : Idx ([s, s, s] ++ [s, s, s]) s :=
  ⟨⟨5, by simp⟩, rfl⟩

-- Small projection facts expose the six concrete context indices to simp.
-- Each is definitional equality; no arithmetic or graph behavior is assumed.
private theorem get_3_0 (s : Shape) (a0 a1 a2 : Tensor ℝ s) :
  TorchLean.TensorPack.get (.cons a0 (.cons a1 (.cons a2 .nil))) (0 : Fin 3) = a0 := rfl

private theorem get_3_1 (s : Shape) (a0 a1 a2 : Tensor ℝ s) :
  TorchLean.TensorPack.get (.cons a0 (.cons a1 (.cons a2 .nil))) (1 : Fin 3) = a1 := rfl

private theorem get_4_2 (s : Shape) (a0 a1 a2 a3 : Tensor ℝ s) :
  TorchLean.TensorPack.get (.cons a0 (.cons a1 (.cons a2 (.cons a3 .nil)))) (2 : Fin 4) = a2 := rfl

private theorem get_4_3 (s : Shape) (a0 a1 a2 a3 : Tensor ℝ s) :
  TorchLean.TensorPack.get (.cons a0 (.cons a1 (.cons a2 (.cons a3 .nil)))) (3 : Fin 4) = a3 := rfl

private theorem get_5_4 (s : Shape) (a0 a1 a2 a3 a4 : Tensor ℝ s) :
  TorchLean.TensorPack.get (.cons a0 (.cons a1 (.cons a2 (.cons a3 (.cons a4 .nil))))) (4 : Fin 5) = a4 := rfl

private theorem get_6_5 (s : Shape) (a0 a1 a2 a3 a4 a5 : Tensor ℝ s) :
  TorchLean.TensorPack.get (.cons a0 (.cons a1 (.cons a2 (.cons a3 (.cons a4 (.cons a5 .nil)))))) (5 : Fin 6) = a5 := rfl

/-- The selected upstream graph output has the stated pointwise polynomial value.
This is independent of the derivative theorem and covers every coordinate. -/
theorem forward_polynomial (s : Shape) (x w b : Tensor ℝ s) (i : Fin (Spec.Shape.size s)) :
    tensorToVec (((affineSquare s).toTypedGraph (output s)).forward
      (.cons x (.cons w (.cons b .nil)))) i =
    (tensorToVec x i * tensorToVec w i + tensorToVec b i) ^ 2 := by
  simp [Runtime.Autograd.Torch.TypedGraph.forward,
    Runtime.Autograd.Torch.TypedGraphWithData.forward, DGraph.toTypedGraph,
    affineSquare, DGraph.snoc, DGraph.nil, Graph.toAlgebra, Algebra.Graph.toData,
    Algebra.GraphData.eval, Node.toAlgebra, TapeNodes.square, TapeNodes.add,
    TapeNodes.mul, Node.ofFn, output, CtxVec.get_flattenCtx, getIdx, TensorPack.snoc,
    Tensor.castShape, vecOfFun, pow_two,
    get_3_0, get_3_1, get_4_2, get_4_3, get_5_4, get_6_5]

/-- The checked API's correctness statement remains explicitly conditional on success. -/
theorem checked_vjp (s : Shape) (inputs : TensorPack ℝ [s, s, s])
    (seed : Tensor ℝ s) (result : TensorPack ℝ [s, s, s] × Tensor ℝ s)
    (success : ((affineSquare s).toTypedGraph (output s)).vjpChecked inputs () seed = .ok result) :
    flattenCtx result.1 =
      (fderiv ℝ (fun x => tensorToVec (((affineSquare s).toTypedGraph (output s)).forward
        (unflattenCtx x))) (flattenCtx inputs)).adjoint (tensorToVec seed) :=
  (affineSquare s).vjpChecked_adjoint_fderiv (output s) inputs seed result success

/-- Every node in this graph has unconditional runtime validation, so the checked
reverse operation succeeds for every real input and seed. -/
theorem checked_success (s : Shape) (inputs : TensorPack ℝ [s, s, s])
    (seed : Tensor ℝ s) :
    let g := (affineSquare s).toTypedGraph (output s)
    g.vjpChecked inputs () seed = .ok (g.vjpWithSeed inputs seed, g.forward inputs) := by
  apply Runtime.Autograd.Torch.TypedGraphWithData.vjpChecked_eq
  rfl

/-- Mathematical VJP for the checked API, with its success premise discharged. -/
theorem checked_success_vjp (s : Shape) (inputs : TensorPack ℝ [s, s, s])
    (seed : Tensor ℝ s) :
    let g := (affineSquare s).toTypedGraph (output s)
    flattenCtx (g.vjpWithSeed inputs seed) =
      (fderiv ℝ (fun x => tensorToVec (g.forward (unflattenCtx x)))
        (flattenCtx inputs)).adjoint (tensorToVec seed) := by
  exact checked_vjp s inputs seed _ (checked_success s inputs seed)

/-- Success and derivative correctness for the lower-level exact generated tape.
No successful-execution or desired-gradient premise is assumed. -/
theorem exact_tape_success_vjp (s : Shape) (inputs : TensorPack ℝ [s, s, s])
    (seed : Tensor ℝ s) :
    let g := (affineSquare s).g.toAlgebra
    let gradients := Algebra.Graph.backpropAllCtx g inputs () (TensorPack.single (output s) seed)
    Runtime.Autograd.Tape.backwardDenseAll
        (Algebra.Graph.lowerGraphToTape g inputs ()).1 (output s).i.1
        (Spec.SomeTensor.ofTensor seed) =
      .ok (TensorPack.toShapeErasedArray gradients)
    ∧ flattenCtx (Algebra.TensorPack.takeLeft gradients) =
      (fderiv ℝ (Graph.evalVec (g.toReal ())) (flattenCtx inputs)).adjoint
        (flattenCtx (TensorPack.single (output s) seed)) := by
  apply Algebra.Graph.backwardDenseAll_lowerGraphToTape_adjoint_fderiv_at
  rw [Algebra.Graph.toAlgebra_toReal]
  exact DGraph.graphFDerivCorrectAtOfCorrect (affineSquare s).hg (flattenCtx inputs)

/-- A narrow joint-library theorem: the unsigned value of the actual modeled
PTX minimum is the value of a real scalar tensor. This is an embedding identity,
not a kernel/network correspondence or a floating-point interpretation. -/
theorem unsigned_min_scalar_embedding (a b : Ptx.Word) :
    Tensor.item (Tensor.scalar ((Ptx.Scalar.BinOp.eval .minU a b).toNat : ℝ)) =
      (Nat.min a.toNat b.toNat : ℝ) := by
  rw [Tensor.item_scalar, Ptx.Scalar.IntegerMinMax.min_toNat]

#print axioms affineSquare
#print axioms forward_polynomial
#print axioms checked_vjp
#print axioms exact_tape_success_vjp
#print axioms checked_success
#print axioms checked_success_vjp
#print axioms unsigned_min_scalar_embedding
end
end PtxTorchLean
